export { default as ScholarshipsSection } from './ScholarshipsSection';
export { default as FacilitiesSection } from './FacilitiesSection';
export { default as UpdatesSection } from './UpdatesSection';
export { default as PlacementSection } from './PlacementSection';
export { default as FAQsSection } from './FAQsSection';
export { default as CoursesSection } from './CoursesSection';
export { default as AdmissionSection } from './AdmissionSection';
export { default as CutoffSection } from './CutoffSection';
export { default as SidebarWidgetsSection } from './SidebarWidgetsSection';
export { default as SeoMetaSection } from './SeoMetaSection';
export { default as LocationSection, indianStates, citiesByState } from './LocationSection';
export { default as MenuConfigSection } from './MenuConfigSection';
