/**
 * URL Helper utilities for admissionbuddy
 * New URL Structure:
 * 
 * Universities:
 * - /university - All universities
 * - /university/{state} - Universities in state
 * - /university/{city} - Universities in city  
 * - /university/{state}/{city} - Universities in state+city
 * - /university/{stream} - Universities by stream
 * - /university/{course} - Universities by course
 * - /university/{stream}/{course} - Universities by stream+course
 * - /university/{state}/{stream} - Universities in state by stream
 * - /university/{city}/{stream} - Universities in city by stream
 * - /university/{state}/{stream}/{course} - Universities in state by stream+course
 * - /university/{city}/{stream}/{course} - Universities in city by stream+course
 * 
 * Colleges: Same pattern with /colleges
 * Schools: /schools, /schools/{state}, /schools/{city}, /schools/{state}/{city}
 */

import { generateSlug } from './slugify';

// Institution type mapping
export const INSTITUTION_TYPES = {
  COLLEGE: 'colleges',
  SCHOOL: 'schools', 
  UNIVERSITY: 'university'
};

// Indian States (slug format)
export const INDIAN_STATES = [
  'andaman-and-nicobar-islands',
  'andhra-pradesh',
  'arunachal-pradesh',
  'assam',
  'bihar',
  'chandigarh',
  'chhattisgarh',
  'dadra-and-nagar-haveli-and-daman-and-diu',
  'delhi',
  'goa',
  'gujarat',
  'haryana',
  'himachal-pradesh',
  'jammu-and-kashmir',
  'jharkhand',
  'karnataka',
  'kerala',
  'ladakh',
  'lakshadweep',
  'madhya-pradesh',
  'maharashtra',
  'manipur',
  'meghalaya',
  'mizoram',
  'nagaland',
  'odisha',
  'puducherry',
  'punjab',
  'rajasthan',
  'sikkim',
  'tamil-nadu',
  'telangana',
  'tripura',
  'uttar-pradesh',
  'uttarakhand',
  'west-bengal'
];

export const STATE_NAMES = {
  'andaman-and-nicobar-islands': 'Andaman and Nicobar Islands',
  'andhra-pradesh': 'Andhra Pradesh',
  'arunachal-pradesh': 'Arunachal Pradesh',
  'assam': 'Assam',
  'bihar': 'Bihar',
  'chandigarh': 'Chandigarh',
  'chhattisgarh': 'Chhattisgarh',
  'dadra-and-nagar-haveli-and-daman-and-diu': 'Dadra and Nagar Haveli and Daman and Diu',
  'delhi': 'Delhi',
  'goa': 'Goa',
  'gujarat': 'Gujarat',
  'haryana': 'Haryana',
  'himachal-pradesh': 'Himachal Pradesh',
  'jammu-and-kashmir': 'Jammu and Kashmir',
  'jharkhand': 'Jharkhand',
  'karnataka': 'Karnataka',
  'kerala': 'Kerala',
  'ladakh': 'Ladakh',
  'lakshadweep': 'Lakshadweep',
  'madhya-pradesh': 'Madhya Pradesh',
  'maharashtra': 'Maharashtra',
  'manipur': 'Manipur',
  'meghalaya': 'Meghalaya',
  'mizoram': 'Mizoram',
  'nagaland': 'Nagaland',
  'odisha': 'Odisha',
  'puducherry': 'Puducherry',
  'punjab': 'Punjab',
  'rajasthan': 'Rajasthan',
  'sikkim': 'Sikkim',
  'tamil-nadu': 'Tamil Nadu',
  'telangana': 'Telangana',
  'tripura': 'Tripura',
  'uttar-pradesh': 'Uttar Pradesh',
  'uttarakhand': 'Uttarakhand',
  'west-bengal': 'West Bengal'
};

// Indian Cities (slug format) - from master data (1672 cities)
export const INDIAN_CITIES = [
  'abohar', 'achalpur', 'adampur', 'adilabad', 'adipur', 'adityapur', 'adoni', 'adoor',
  'adyar', 'afzalpur', 'agartala', 'agatti', 'agra', 'ahmedabad', 'ahmedgarh', 'ahmednagar',
  'aizawl', 'ajmer', 'ajnala', 'akbarpur', 'akola', 'aland', 'alandur', 'alappuzha',
  'alathur', 'alawalpur', 'alibag', 'aligarh', 'alipurduar', 'allahabad', 'almora', 'along',
  'alur', 'aluva', 'alwal', 'alwar', 'amaravati', 'amargarh', 'ambah', 'ambala',
  'ambalapuzha', 'ambarnath', 'ambattur', 'ambikapur', 'ambur', 'amethi', 'amla', 'amloh',
  'amravati', 'amreli', 'amritsar', 'amroha', 'amta', 'anand', 'anandnagar', 'anandpur-sahib',
  'anantapur', 'anantnag', 'andana', 'anekal', 'angamaly', 'angul', 'anjar', 'anpara',
  'anuppur', 'arakalgud', 'arakkonam', 'arambagh', 'arani', 'araria', 'arni', 'arrah',
  'arsha', 'arsikere', 'aruppukkottai', 'asansol', 'asifabad', 'assandh', 'aswapuram', 'ater',
  'athani', 'attingal', 'attur', 'aur', 'aurad', 'aurai', 'aurangabad', 'avadi',
  'ayodhya', 'azamgarh', 'baba-bakala', 'badami', 'baddi', 'badlapur', 'badrinath', 'bagaha',
  'bagalkot', 'bagepalli', 'bageshwar', 'baghapurana', 'bagmundi', 'bagnan', 'bahadurgarh', 'baharampur',
  'bahraich', 'baidyabati', 'bairad', 'balachaur', 'balagarh', 'balaghat', 'balarampur', 'balasore',
  'baldeogarh', 'baleshwar', 'balikuda', 'balimela', 'ballia', 'balod', 'baloda-bazar', 'balrampur',
  'balurghat', 'banbasa', 'banda', 'bandel', 'bandhugaon', 'bandlaguda', 'bandwan', 'banga',
  'bangalore', 'bangaon', 'bangarpet', 'banka', 'bankura', 'bansgaon', 'bansi', 'bansur',
  'banswara', 'bantwal', 'barabanki', 'baramulla', 'baran', 'baranagar', 'barasat', 'barbil',
  'bardhaman', 'bareilly', 'bargarh', 'bargur', 'barh', 'baripada', 'barjora', 'barmer',
  'barnala', 'barrackpore', 'barshi', 'baruipur', 'barwala', 'basavakalyan', 'basirhat', 'bassi-pathana',
  'basti', 'batala', 'bathinda', 'bavla', 'bayana', 'bazarhathnoor', 'bazpur', 'beawar',
  'beed', 'begowal', 'begusarai', 'behror', 'bela', 'belgaum', 'bellampally', 'bellary',
  'belonia', 'belthangady', 'belur', 'bemetara', 'berhampur', 'berinag', 'bettiah', 'betul',
  'bhachau', 'bhadrachalam', 'bhadrak', 'bhadravati', 'bhagalpur', 'bhagwanpur', 'bhalki', 'bharatpur',
  'bharuch', 'bhatpara', 'bhatwari', 'bhavnagar', 'bhawanigarh', 'bhawanipatna', 'bheemini', 'bhilai',
  'bhilwara', 'bhimavaram', 'bhimtal', 'bhind', 'bhinga', 'bhiwandi', 'bhiwani', 'bhiwapur',
  'bhogpur', 'bholath', 'bhongir', 'bhopal', 'bhowali', 'bhubaneswar', 'bhucho-mandi', 'bhuj',
  'bhusawal', 'bhuvanagiri', 'bicholim', 'bidar', 'bihar-sharif', 'biharsharif', 'bijapur', 'bijnor',
  'bikaner', 'bikramganj', 'bilaspur', 'bilga', 'bilsanda', 'bina', 'biridi', 'bisalpur',
  'bishnupur', 'bissam-cuttack', 'bistupur', 'boath', 'boden', 'bodh-gaya', 'boduppal', 'boipariguda',
  'boisar', 'bokaro', 'bolpur', 'bomdila', 'bonakal', 'bongaigaon', 'borigumma', 'borsad',
  'botad', 'brahmagiri', 'brahmapur', 'brahmavar', 'budaun', 'budge-budge', 'bulandshahr', 'bundi',
  'burgampahad', 'burhanpur', 'buxar', 'byadgi', 'byndoor', 'canning', 'car-nicobar', 'central-delhi',
  'chaibasa', 'chakdaha', 'chakia', 'chalakudy', 'challakere', 'chamarajanagar', 'chamba', 'chamoli',
  'champa', 'champadanga', 'champawat', 'champhai', 'chandabali', 'chandahandi', 'chandannagar', 'chandauli',
  'chandausi', 'chandigarh', 'chandili', 'chandipur', 'chandrapur', 'chandrugonda', 'chandur', 'changanassery',
  'channagiri', 'channapatna', 'channarayapatna', 'chas', 'chatra', 'chavakkad', 'chengalpattu', 'chengannur',
  'chennai', 'chennur', 'cherla', 'cherpulassery', 'cherthala', 'cheyyar', 'cheyyur', 'chhachhrauli',
  'chhapra', 'chhatarpur', 'chhatna', 'chhindwara', 'chhota-udaipur', 'chikballapur', 'chikhli', 'chikkanayakanahalli',
  'chikmagalur', 'chikodi', 'chilakaluripet', 'chillupar', 'chincholi', 'chinnasalem', 'chinsurah', 'chintamani',
  'chinyalisaur', 'chiplun', 'chirala', 'chirayinkeezhu', 'chitapur', 'chitradurga', 'chitrakonda', 'chittoor',
  'chittorgarh', 'chittur', 'chopan', 'choutuppal', 'chrompet', 'churachandpur', 'churk', 'churu',
  'coimbatore', 'contai', 'cooch-behar', 'cuddalore', 'cuttack', 'dabhoi', 'dabugam', 'dabwali',
  'dahanu', 'dahegam', 'dahod', 'daman', 'dameracherla', 'damoh', 'danapur', 'dankuni',
  'dantewada', 'dapoli', 'darbhanga', 'darjeeling', 'darwha', 'dasmantpur', 'dasuya', 'datia',
  'dausa', 'davanagere', 'davangere', 'deeg', 'deesa', 'dehlon', 'dehradun', 'dehri',
  'delang', 'delhi', 'deoghar', 'deori', 'deoria', 'dera-baba-nanak', 'deulgaon-raja', 'devadurga',
  'devanahalli', 'devarakonda', 'devprayag', 'devrukh', 'dewas', 'dhamnagar', 'dhamtari', 'dhanaulti',
  'dhanbad', 'dhaniakhali', 'dharamgarh', 'dharamkot', 'dharamshala', 'dharchula', 'dharmanagar', 'dharmapuri',
  'dharmavaram', 'dharwad', 'dhaulpur', 'dhenkanal', 'dhilwan', 'dholka', 'dholpur', 'dhoraji',
  'dhubri', 'dhule', 'dhulian', 'dhuri', 'diamond-harbour', 'dibrugarh', 'didihat', 'digras',
  'dimapur', 'dinanagar', 'dindigul', 'dindori', 'diphu', 'dirba', 'diu', 'doddaballapur',
  'doiwala', 'domjur', 'doraha', 'dornakal', 'dronagiri', 'duddhi', 'dugadda', 'dumka',
  'dummagudem', 'dunda', 'dungarpur', 'durg', 'durgapur', 'dwarahat', 'dwarka', 'east-delhi',
  'edappadi', 'ellenabad', 'eluru', 'enkoor', 'erode', 'ersama', 'etah', 'etawah',
  'ettumanoor', 'faizabad', 'falta', 'faridabad', 'faridkot', 'farrukhabad', 'fatehabad', 'fatehgarh-churian',
  'fatehgarh-sahib', 'fatehpur', 'fazilka', 'fazilnagar', 'ferozepur-cantt', 'ferozepur-jhirka', 'firozabad', 'firozpur',
  'forbesganj', 'gadag', 'gadarpur', 'gadarwara', 'gainsari', 'gairsain', 'gandhidham', 'gandhinagar',
  'gangajalghati', 'gangapur-city', 'gangavalli', 'gangavathi', 'gangolihat', 'gangotri', 'gangtok', 'garhshankar',
  'garhwa', 'gariaband', 'gauribidanur', 'gaya', 'gayeshpur', 'ghanaur', 'ghansali', 'gharaunda',
  'ghatkesar', 'ghaziabad', 'ghazipur', 'ghosi', 'gidderbaha', 'gill', 'gingee', 'giridih',
  'gobindgarh', 'godda', 'godhra', 'goghat', 'gohad', 'gohana', 'goindwal-sahib', 'gokak',
  'gonda', 'gondal', 'gondia', 'goniana', 'gop', 'gopalganj', 'gorakhpur', 'goraya',
  'govindgarh', 'govindpur', 'greater-noida', 'gubbi', 'gudari', 'gudivada', 'gudiyattam', 'guduvancheri',
  'guhagar', 'guindy', 'gulbarga', 'guledgudda', 'gumla', 'gummidipoondi', 'guna', 'gundala',
  'gundlupet', 'guntakal', 'guntur', 'gunupur', 'gurdaspur', 'guru-har-sahai', 'gurugram', 'guruvayoor',
  'guwahati', 'gwalior', 'gyalshing', 'gyanpur', 'h-d-kote', 'habra', 'hajipur', 'haldia',
  'haldwani', 'haliya', 'halol', 'hamirpur', 'hansi', 'hanumangarh', 'hapur', 'hardoi',
  'hariana', 'haridwar', 'harihar', 'haripad', 'haripal', 'harur', 'hassan', 'hata',
  'hathiundha', 'hathras', 'haveri', 'hayathnagar', 'hazaribagh', 'herbertpur', 'himatnagar', 'hindaun',
  'hindupur', 'hinganghat', 'hingna', 'hirbandh', 'hirekerur', 'hisar', 'hodal', 'holalkere',
  'holenarasipur', 'honnali', 'hooghly', 'hosadurga', 'hosakote', 'hosdurg', 'hoshangabad', 'hoshiarpur',
  'hospet', 'hosur', 'howrah', 'hubli', 'hukkeri', 'humnabad', 'hungund', 'hunsur',
  'hura', 'hussainiwala', 'huzurnagar', 'hyderabad', 'ichalkaranji', 'ichoda', 'idar', 'ikauna',
  'ilkal', 'imphal', 'indas', 'indi', 'indore', 'indravelly', 'irinjalakuda', 'iritty',
  'itanagar', 'itarsi', 'jabalpur', 'jagadhri', 'jagalur', 'jagatballavpur', 'jagatsinghpur', 'jagdalpur',
  'jagraon', 'jagtial', 'jahanabad', 'jainad', 'jainoor', 'jaipatna', 'jaipur', 'jajpur',
  'jalalabad', 'jalandhar', 'jaleswar', 'jalgaon', 'jalna', 'jalpaiguri', 'jamkhandi', 'jammu',
  'jamnagar', 'jamshedpur', 'jamtara', 'jamui', 'jandiala-guru', 'jangaon', 'jangipur', 'janjgir',
  'jannaram', 'jarwal', 'jaspur', 'jatara', 'jaunpur', 'jawhar', 'jaynagar', 'jaypur',
  'jehanabad', 'jetpur', 'jeypore', 'jhabrera', 'jhalda', 'jhansi', 'jharigam', 'jharsuguda',
  'jhunjhunu', 'jind', 'jirat', 'jodhpur', 'jorhat', 'joshimath', 'joura', 'jowai',
  'joynagar', 'joypur', 'jugsalai', 'julurupadu', 'junagadh', 'junagarh', 'kadapa', 'kadi',
  'kadma', 'kadur', 'kagaznagar', 'kailaras', 'kailashahar', 'kaisarganj', 'kaithal', 'kakatpur',
  'kakching', 'kakdwip', 'kakinada', 'kalahandi', 'kalampur', 'kalanaur', 'kalayat', 'kalimela',
  'kalka', 'kallakurichi', 'kallur', 'kalmeshwar', 'kalol', 'kalpakkam', 'kalpetta', 'kalyan-dombivali',
  'kalyani', 'kalyansinghpur', 'kamarhati', 'kamothe', 'kamptee', 'kanakapura', 'kanas', 'kanchipuram',
  'kanchrapara', 'kanhangad', 'kankavli', 'kanker', 'kannur', 'kanpur', 'kapkot', 'kapra',
  'kaptanganj', 'kapurthala', 'karad', 'karahal', 'karaikal', 'karaikkudi', 'karanja-lad', 'karauli',
  'kargil', 'karimnagar', 'karjat', 'karkala', 'karnal', 'karnaprayag', 'kartarpur', 'karunagappally',
  'karur', 'kasaragod', 'kasganj', 'kashipur', 'kasia', 'kathua', 'kathumar', 'katihar',
  'katni', 'katol', 'katra', 'katra-bazar', 'kausani', 'kavali', 'kavaratti', 'kaveripakkam',
  'kawardha', 'kayamkulam', 'kedarnath', 'keesara', 'kelambakkam', 'kendrapara', 'kendujhar', 'keonjhar',
  'kerakat', 'kerimeri', 'kesamudram', 'keshod', 'kesinga', 'khadda', 'khadur-sahib', 'khagaria',
  'khalilabad', 'khamanon', 'khambhat', 'khamgaon', 'khammam', 'khanakul', 'khandwa', 'khanna',
  'kharagpur', 'kharar', 'kharghar', 'khargone', 'khariar', 'khatima', 'khatra', 'khed',
  'kheda', 'khesraha', 'khopoli', 'khurai', 'khurja', 'kichha', 'kilimanoor', 'kishanganj',
  'kishangarh', 'kishangarh-bas', 'kochi', 'kodad', 'kodambakkam', 'koderma', 'kodungallur', 'kohima',
  'kolar', 'kolasib', 'kolhapur', 'kolkata', 'kollam', 'kollegal', 'kolli-hills', 'kolnara',
  'komna', 'kompally', 'konark', 'kondagaon', 'kondotty', 'kopaganj', 'koppa', 'koppal',
  'koraput', 'koratagere', 'korba', 'korukonda', 'kosagumuda', 'kota', 'kotdwar', 'kothagudem',
  'kothamangalam', 'kotkapura', 'kotkasim', 'kotpad', 'kottarakkara', 'kottayam', 'kotulpur', 'koyilandy',
  'kozhikode', 'krishnagiri', 'krishnanagar', 'krishnarajanagara', 'krushnaprasad', 'kudal', 'kudumuluguma', 'kuhi',
  'kujang', 'kukatpally', 'kullu', 'kultali', 'kumarapalayam', 'kumbakonam', 'kumher', 'kundapura',
  'kundrathur', 'kunigal', 'kunnamkulam', 'kuravi', 'kurnool', 'kushtagi', 'kusumanchi', 'kuthuparamba',
  'kuttanad', 'kyathampalli', 'ladwa', 'lahar', 'lakhimpur', 'lakhisarai', 'laksar', 'lalitpur',
  'lambi', 'lamtaput', 'landhaura', 'lanja', 'lanjigarh', 'lansdowne', 'latehar', 'latur',
  'laundi', 'laxmangarh', 'laxmipur', 'lb-nagar', 'leh', 'lehragaga', 'lingasugur', 'lohaghat',
  'lohardaga', 'lohian-khas', 'lonar', 'longowal', 'lucknow', 'ludhiana', 'lunawada', 'lunglei',
  'luxettipet', 'machhali-shahar', 'machhiwara', 'machilipatnam', 'madanapalle', 'madhavaram', 'madhira', 'madhubani',
  'madhugiri', 'madhupur', 'madurai', 'madurantakam', 'magadi', 'magrahat', 'mahabaleshwar', 'mahabubabad',
  'mahad', 'maharajpur', 'mahasamund', 'mahbubnagar', 'mahe', 'mahsi', 'mahuva', 'maihar',
  'mailam', 'mainpuri', 'majitha', 'makhu', 'makrana', 'malakhera', 'malappuram', 'malda',
  'malegaon', 'malerkotla', 'malhani', 'malkajgiri', 'malkangiri', 'malout', 'malthone', 'malur',
  'malvan', 'mamallapuram', 'mamdot', 'manali', 'mananthavady', 'manavadar', 'manbazar', 'mancherial',
  'mandamarri', 'mandangad', 'mandi', 'mandla', 'mandsaur', 'mandvi', 'mandya', 'mangalagiri',
  'mangalore', 'mangan', 'mangaon', 'manglaur', 'mango', 'mangrol', 'mangrulpir', 'manipal',
  'manjeri', 'mankapur', 'mannarkad', 'manora', 'mansa', 'manuguru', 'manvi', 'mapusa',
  'marakkanam', 'margao', 'mariahu', 'maripeda', 'markapur', 'marshaghai', 'mathili', 'mathura',
  'mathurapur', 'mattannur', 'mau', 'maunath-bhanjan', 'maur-mandi', 'mavelikara', 'mayurbhanj', 'medavakkam',
  'medchal', 'medininagar', 'medinipur', 'meerpet', 'meerut', 'mehatpur', 'mehgaon', 'mehkar',
  'mehsana', 'mejia', 'melmalaiyanur', 'melmaruvathur', 'menhdawal', 'mettur', 'mhasla', 'midnapore',
  'minicoy', 'mira-bhayandar', 'miraj', 'miryalaguda', 'miryalguda', 'mirzapur', 'miyapur', 'modasa',
  'modinagar', 'moga', 'mogra', 'mohali', 'mohammadabad', 'mohgaon', 'mohpa', 'mokama',
  'mokhada', 'mokokchung', 'molakalmuru', 'moonak', 'moradabad', 'morappur', 'morbi', 'morena',
  'mori', 'morinda', 'mothkur', 'motihari', 'mouda', 'muddebihal', 'mudgal', 'mudhol',
  'mudigere', 'mughalsarai', 'muhammadabad-gohna', 'mukerian', 'mukteshwar', 'muktsar', 'mulakalapalli', 'mulbagal',
  'mullanpur-dakha', 'multai', 'mumbai', 'mundargi', 'mundawar', 'mungeli', 'munger', 'mungra-badshahpur',
  'muniguda', 'munsyari', 'munugode', 'murud', 'murwara', 'mussoorie', 'muvattupuzha', 'muzaffarnagar',
  'muzaffarpur', 'myorpur', 'mysore', 'nabadwip', 'nabha', 'nabrangpur', 'nacharam', 'nadbai',
  'nadiad', 'nagal', 'nagaon', 'nagapattinam', 'nagar', 'nagarjunasagar', 'nagaur', 'nagda',
  'nagercoil', 'nagod', 'nagole', 'nagpur', 'nagpur-rural', 'nagwa', 'nahan', 'naharlagun',
  'naihati', 'nainital', 'nakhatrana', 'nakodar', 'nakrekal', 'nalanda', 'nalasopara', 'nalgonda',
  'namakkal', 'namchi', 'namkhana', 'nandapur', 'nandura', 'nandurbar', 'nandyal', 'nangal',
  'nanjangud', 'narasapuram', 'narasaraopet', 'narasimharajapura', 'narayanpatna', 'narayanpur', 'narendranagar', 'nargund',
  'narketpally', 'narkhed', 'narla', 'narmadapuram', 'narnaul', 'narnaund', 'narnoor', 'narsampet',
  'narsinghpur', 'narwana', 'nashik', 'nathana', 'nathdwara', 'natrampalli', 'naugachhia', 'nautanwa',
  'navi-mumbai', 'navsari', 'nawabganj', 'nawada', 'nawanshahr', 'nedumangad', 'neemrana', 'neemuch',
  'nekkonda', 'nelamangala', 'nellikuduru', 'nellore', 'nemmara', 'nennal', 'neturia', 'new-delhi',
  'new-tehri', 'neyveli', 'neyyattinkara', 'nhava-sheva', 'nihal-singh-wala', 'nilagiri', 'nimapara', 'nimbahera',
  'nirmal', 'nischintakoili', 'niwari', 'nizamabad', 'noida', 'nongstoin', 'north-delhi', 'nuapada',
  'nuh', 'nurmahal', 'obra', 'omalur', 'onda', 'ongole', 'oragadam', 'orai',
  'orchha', 'osmanabad', 'ottapalam', 'pachmarhi', 'pachperwa', 'padampur', 'padia', 'padrauna',
  'pahari', 'pakhowal', 'pakur', 'pala', 'palacode', 'palakkad', 'palakollu', 'palakurthy',
  'palampur', 'palanpur', 'palasa', 'palghar', 'pali', 'palitana', 'pallavaram', 'palvancha',
  'palwal', 'pammal', 'panaji', 'panchgani', 'panchkula', 'panchla', 'pandalam', 'pandhurna',
  'pandua', 'panihati', 'panipat', 'panna', 'pantnagar', 'panvel', 'paonta-sahib', 'papadahandi',
  'para', 'paradip', 'paramathi', 'parappanangadi', 'paraswada', 'parbhani', 'parkal', 'parseoni',
  'pasighat', 'patan', 'pathanamthitta', 'pathankot', 'patharpratima', 'pathri', 'patiala', 'patna',
  'patran', 'patrasayer', 'pattambi', 'pattamundai', 'patti', 'pauri', 'pavagada', 'payagpur',
  'payal', 'payyannur', 'payyanur', 'peddavoora', 'peerzadiguda', 'pehowa', 'pen', 'pennagaram',
  'penuballi', 'perinthalmanna', 'periyapatna', 'pernambut', 'perumbavoor', 'perungudi', 'petlad', 'phagwara',
  'phaltan', 'pharenda', 'phephna', 'phillaur', 'phulwari-sharif', 'phusro', 'pilibhit', 'pimpri-chinchwad',
  'pinapaka', 'pinjore', 'pipariya', 'pipili', 'pipraich', 'piravom', 'piriyapatna', 'pithampur',
  'pithoragarh', 'pochampalli', 'pocharam', 'podia', 'polba', 'pollachi', 'polur', 'ponda',
  'ponnani', 'ponneri', 'poonamallee', 'porbandar', 'porsa', 'port-blair', 'porur', 'pottangi',
  'pratapgarh', 'pratapnagar', 'prayagraj', 'prithvipur', 'proddatur', 'puducherry', 'pulwama', 'punalur',
  'puncha', 'pundri', 'pune', 'puranpur', 'puri', 'purnagiri', 'purnia', 'purola',
  'pursurah', 'purulia', 'pusad', 'puttaparthi', 'puttur', 'qadian', 'quthbullapur', 'radaur',
  'raebareli', 'raghunathpally', 'raghunathpur', 'rahatgarh', 'raibag', 'raichur', 'raiganj', 'raigarh',
  'raighar', 'raikot', 'raipur', 'rajahmundry', 'rajapalayam', 'rajapur', 'rajgarh', 'rajgir',
  'rajkanika', 'rajkot', 'rajnagar', 'rajnandgaon', 'rajpur', 'rajpura', 'rajsamand', 'ramagundam',
  'ramanagara', 'ramannapet', 'ramdurg', 'ramgarh', 'ramnagar', 'rampur', 'rampura-phul', 'ramtek',
  'ranaghat', 'ranchi', 'ranebennuru', 'rangpo', 'ranibandh', 'ranibennur', 'ranikhet', 'ranipet',
  'ranni', 'rapar', 'rasipuram', 'rasra', 'ratia', 'ratlam', 'ratnagiri', 'rayagada',
  'rayya', 'rebbena', 'rehli', 'renukoot', 'rewa', 'rewari', 'rishikesh', 'rishra',
  'risod', 'robertsganj', 'robertson-pet', 'roha', 'rohini', 'rohtak', 'ron', 'roorkee',
  'ropar', 'rosera', 'rourkela', 'rudhauli', 'rudrapur', 'rupbas', 'sabalgarh', 'sadhaura',
  'safidon', 'sagar', 'saharanpur', 'saharsa', 'sahebganj', 'sahjanwa', 'sahnewal', 'saidpur',
  'sakchi', 'saket', 'sakleshpur', 'sakti', 'salem', 'salempur', 'saltora', 'samalkha',
  'samana', 'samastipur', 'sambalpur', 'sambhal', 'samrala', 'sanand', 'sangameshwar', 'sangat',
  'sangli', 'sangrur', 'sankagiri', 'sankarapuram', 'sankrail', 'santipur', 'santrampur', 'santuri',
  'saoner', 'sarenga', 'saroornagar', 'sasaram', 'satara', 'sathupalli', 'satna', 'satpuli',
  'satyabadi', 'saundatti', 'sausar', 'savanur', 'sawai-madhopur', 'sawantwadi', 'secunderabad', 'sedam',
  'sehore', 'semiliguda', 'senthamangalam', 'seoni', 'seraikela', 'serampore', 'serchhip', 'sewar',
  'sewarhi', 'shahabad', 'shahdol', 'shahganj', 'shahjahanpur', 'shahkot', 'shahpur', 'shamshabad',
  'shantipur', 'shegaon', 'sheikhpura', 'sheopur', 'sheoraphuli', 'sherpur', 'shiggaon', 'shikaripura',
  'shikohabad', 'shillong', 'shimla', 'shimoga', 'shirala', 'shivpuri', 'sholinganallur', 'shoranur',
  'shorapur', 'shravasti', 'shrivardhan', 'shyampur', 'siddipet', 'sidhwan-bet', 'sidlaghatta', 'sihor',
  'sihora', 'sikanderpur', 'sikar', 'silchar', 'siliguri', 'silvassa', 'simdega', 'simlapal',
  'simulia', 'sinapali', 'sindgi', 'sindhanur', 'sindhudurg', 'sindkhed-raja', 'singareni', 'singrauli',
  'singur', 'sira', 'sirhind', 'sirpur', 'sirsa', 'siruseri', 'siswa-bazaar', 'sitamarhi',
  'sitapur', 'sitarganj', 'sivakasi', 'siwan', 'sohna', 'solan', 'solapur', 'someshwar',
  'sonamukhi', 'sonari', 'sonarpur', 'sonbhadra', 'sonipat', 'sopore', 'sorab', 'soro',
  'south-delhi', 'sri-ganganagar', 'sri-hargobindpur', 'srikakulam', 'srinagar', 'sringeri', 'srinivaspur', 'sriperumbudur',
  'station-ghanpur', 'sudhar', 'sujangarh', 'sujanpur', 'sukma', 'sullia', 'sultan-bathery', 'sultanpur',
  'sultanpur-lodhi', 'sunabeda', 'sunam', 'sundernagar', 'supaul', 'surajpur', 'surat', 'surendranagar',
  'surpur', 'suryapet', 't-narasipur', 'tadepalligudem', 'tadipatri', 'talamadugu', 'talasari', 'taldangra',
  'taloja', 'talwandi-sabo', 'talwara', 'tambaram', 'tamkuhi-road', 'tamluk', 'tanakpur', 'tanda-urmur',
  'tanur', 'tapukara', 'tarakeswar', 'taraori', 'tarikere', 'tarn-taran', 'tawang', 'tehri',
  'tekulapalli', 'telco', 'tenali', 'tentulikhunti', 'tezpur', 'tezu', 'thalaivasal', 'thalassery',
  'thanagazi', 'thane', 'thanesar', 'thanjavur', 'tharali', 'thirunavalur', 'thiruporur', 'thiruvalla',
  'thiruvananthapuram', 'thiruverkadu', 'thodupuzha', 'thoothukudi', 'thorrur', 'thoubal', 'thrissur', 'thuamul-rampur',
  'tihidi', 'tijara', 'tikamgarh', 'tindivanam', 'tinsukia', 'tiptur', 'tirthahalli', 'tirtol',
  'tiruchengode', 'tiruchirappalli', 'tirukoilur', 'tirunelveli', 'tirupati', 'tirupattur', 'tiruppur', 'tirur',
  'tiruttani', 'tiruvannamalai', 'tiruvottiyur', 'tiryani', 'titagarh', 'tohana', 'tonk', 'tuensang',
  'tulsipur', 'tumkur', 'tura', 'turtipar', 'turuvekere', 'uchhain', 'udaipur', 'udaynarayanpur',
  'udgir', 'udhagamandalam', 'udhampur', 'udupi', 'ujjain', 'ulhasnagar', 'uluberia', 'ulundurpet',
  'umaria', 'umarkote', 'umred', 'umreth', 'una', 'unjha', 'unnao', 'upleta',
  'uppal', 'uran', 'urapakkam', 'uska-bazaar', 'uthangarai', 'uthiramerur', 'uthukkottai', 'utnoor',
  'utraula', 'uttarkashi', 'uttarpara', 'vadakara', 'vadodara', 'vaikom', 'valasaravakkam', 'valsad',
  'vanasthalipuram', 'vandalur', 'vandavasi', 'vaniyambadi', 'vanur', 'vapi', 'varanasi', 'varkala',
  'vasai-virar', 'vasco-da-gama', 'vatakara', 'velachery', 'vellore', 'velur', 'vengurla', 'venkatapuram',
  'veraval', 'verka', 'vidisha', 'vijayawada', 'vijaypur', 'vikasnagar', 'vikramgad', 'viluppuram',
  'vinukonda', 'viramgam', 'virudhunagar', 'visakhapatnam', 'visavadar', 'visnagar', 'vizianagaram', 'vrindavan',
  'wada', 'wadakkancherry', 'wai', 'walajabad', 'wankaner', 'wankidi', 'warangal', 'waraseoni',
  'wardha', 'wardhannapet', 'washim', 'weir', 'west-delhi', 'williamnagar', 'wokha', 'wyra',
  'yadagirigutta', 'yadgir', 'yamkeshwar', 'yamunanagar', 'yamunotri', 'yanam', 'yavatmal', 'yelandur',
  'yelburga', 'yellandu', 'yercaud', 'zamania', 'zira', 'zirakpur', 'ziro', 'zunheboto'
];

// City name mapping (slug to display name) - 1672 cities
export const CITY_NAMES = {
  'abohar': 'Abohar',
  'achalpur': 'Achalpur',
  'adampur': 'Adampur',
  'adilabad': 'Adilabad',
  'adipur': 'Adipur',
  'adityapur': 'Adityapur',
  'adoni': 'Adoni',
  'adoor': 'Adoor',
  'adyar': 'Adyar',
  'afzalpur': 'Afzalpur',
  'agartala': 'Agartala',
  'agatti': 'Agatti',
  'agra': 'Agra',
  'ahmedabad': 'Ahmedabad',
  'ahmedgarh': 'Ahmedgarh',
  'ahmednagar': 'Ahmednagar',
  'aizawl': 'Aizawl',
  'ajmer': 'Ajmer',
  'ajnala': 'Ajnala',
  'akbarpur': 'Akbarpur',
  'akola': 'Akola',
  'aland': 'Aland',
  'alandur': 'Alandur',
  'alappuzha': 'Alappuzha',
  'alathur': 'Alathur',
  'alawalpur': 'Alawalpur',
  'alibag': 'Alibag',
  'aligarh': 'Aligarh',
  'alipurduar': 'Alipurduar',
  'allahabad': 'Allahabad',
  'almora': 'Almora',
  'along': 'Along',
  'alur': 'Alur',
  'aluva': 'Aluva',
  'alwal': 'Alwal',
  'alwar': 'Alwar',
  'amaravati': 'Amaravati',
  'amargarh': 'Amargarh',
  'ambah': 'Ambah',
  'ambala': 'Ambala',
  'ambalapuzha': 'Ambalapuzha',
  'ambarnath': 'Ambarnath',
  'ambattur': 'Ambattur',
  'ambikapur': 'Ambikapur',
  'ambur': 'Ambur',
  'amethi': 'Amethi',
  'amla': 'Amla',
  'amloh': 'Amloh',
  'amravati': 'Amravati',
  'amreli': 'Amreli',
  'amritsar': 'Amritsar',
  'amroha': 'Amroha',
  'amta': 'Amta',
  'anand': 'Anand',
  'anandnagar': 'Anandnagar',
  'anandpur-sahib': 'Anandpur Sahib',
  'anantapur': 'Anantapur',
  'anantnag': 'Anantnag',
  'andana': 'Andana',
  'anekal': 'Anekal',
  'angamaly': 'Angamaly',
  'angul': 'Angul',
  'anjar': 'Anjar',
  'anpara': 'Anpara',
  'anuppur': 'Anuppur',
  'arakalgud': 'Arakalgud',
  'arakkonam': 'Arakkonam',
  'arambagh': 'Arambagh',
  'arani': 'Arani',
  'araria': 'Araria',
  'arni': 'Arni',
  'arrah': 'Arrah',
  'arsha': 'Arsha',
  'arsikere': 'Arsikere',
  'aruppukkottai': 'Aruppukkottai',
  'asansol': 'Asansol',
  'asifabad': 'Asifabad',
  'assandh': 'Assandh',
  'aswapuram': 'Aswapuram',
  'ater': 'Ater',
  'athani': 'Athani',
  'attingal': 'Attingal',
  'attur': 'Attur',
  'aur': 'Aur',
  'aurad': 'Aurad',
  'aurai': 'Aurai',
  'aurangabad': 'Aurangabad',
  'avadi': 'Avadi',
  'ayodhya': 'Ayodhya',
  'azamgarh': 'Azamgarh',
  'baba-bakala': 'Baba Bakala',
  'badami': 'Badami',
  'baddi': 'Baddi',
  'badlapur': 'Badlapur',
  'badrinath': 'Badrinath',
  'bagaha': 'Bagaha',
  'bagalkot': 'Bagalkot',
  'bagepalli': 'Bagepalli',
  'bageshwar': 'Bageshwar',
  'baghapurana': 'Baghapurana',
  'bagmundi': 'Bagmundi',
  'bagnan': 'Bagnan',
  'bahadurgarh': 'Bahadurgarh',
  'baharampur': 'Baharampur',
  'bahraich': 'Bahraich',
  'baidyabati': 'Baidyabati',
  'bairad': 'Bairad',
  'balachaur': 'Balachaur',
  'balagarh': 'Balagarh',
  'balaghat': 'Balaghat',
  'balarampur': 'Balarampur',
  'balasore': 'Balasore',
  'baldeogarh': 'Baldeogarh',
  'baleshwar': 'Baleshwar',
  'balikuda': 'Balikuda',
  'balimela': 'Balimela',
  'ballia': 'Ballia',
  'balod': 'Balod',
  'baloda-bazar': 'Baloda Bazar',
  'balrampur': 'Balrampur',
  'balurghat': 'Balurghat',
  'banbasa': 'Banbasa',
  'banda': 'Banda',
  'bandel': 'Bandel',
  'bandhugaon': 'Bandhugaon',
  'bandlaguda': 'Bandlaguda',
  'bandwan': 'Bandwan',
  'banga': 'Banga',
  'bangalore': 'Bangalore',
  'bangaon': 'Bangaon',
  'bangarpet': 'Bangarpet',
  'banka': 'Banka',
  'bankura': 'Bankura',
  'bansgaon': 'Bansgaon',
  'bansi': 'Bansi',
  'bansur': 'Bansur',
  'banswara': 'Banswara',
  'bantwal': 'Bantwal',
  'barabanki': 'Barabanki',
  'baramulla': 'Baramulla',
  'baran': 'Baran',
  'baranagar': 'Baranagar',
  'barasat': 'Barasat',
  'barbil': 'Barbil',
  'bardhaman': 'Bardhaman',
  'bareilly': 'Bareilly',
  'bargarh': 'Bargarh',
  'bargur': 'Bargur',
  'barh': 'Barh',
  'baripada': 'Baripada',
  'barjora': 'Barjora',
  'barmer': 'Barmer',
  'barnala': 'Barnala',
  'barrackpore': 'Barrackpore',
  'barshi': 'Barshi',
  'baruipur': 'Baruipur',
  'barwala': 'Barwala',
  'basavakalyan': 'Basavakalyan',
  'basirhat': 'Basirhat',
  'bassi-pathana': 'Bassi Pathana',
  'basti': 'Basti',
  'batala': 'Batala',
  'bathinda': 'Bathinda',
  'bavla': 'Bavla',
  'bayana': 'Bayana',
  'bazarhathnoor': 'Bazarhathnoor',
  'bazpur': 'Bazpur',
  'beawar': 'Beawar',
  'beed': 'Beed',
  'begowal': 'Begowal',
  'begusarai': 'Begusarai',
  'behror': 'Behror',
  'bela': 'Bela',
  'belgaum': 'Belgaum',
  'bellampally': 'Bellampally',
  'bellary': 'Bellary',
  'belonia': 'Belonia',
  'belthangady': 'Belthangady',
  'belur': 'Belur',
  'bemetara': 'Bemetara',
  'berhampur': 'Berhampur',
  'berinag': 'Berinag',
  'bettiah': 'Bettiah',
  'betul': 'Betul',
  'bhachau': 'Bhachau',
  'bhadrachalam': 'Bhadrachalam',
  'bhadrak': 'Bhadrak',
  'bhadravati': 'Bhadravati',
  'bhagalpur': 'Bhagalpur',
  'bhagwanpur': 'Bhagwanpur',
  'bhalki': 'Bhalki',
  'bharatpur': 'Bharatpur',
  'bharuch': 'Bharuch',
  'bhatpara': 'Bhatpara',
  'bhatwari': 'Bhatwari',
  'bhavnagar': 'Bhavnagar',
  'bhawanigarh': 'Bhawanigarh',
  'bhawanipatna': 'Bhawanipatna',
  'bheemini': 'Bheemini',
  'bhilai': 'Bhilai',
  'bhilwara': 'Bhilwara',
  'bhimavaram': 'Bhimavaram',
  'bhimtal': 'Bhimtal',
  'bhind': 'Bhind',
  'bhinga': 'Bhinga',
  'bhiwandi': 'Bhiwandi',
  'bhiwani': 'Bhiwani',
  'bhiwapur': 'Bhiwapur',
  'bhogpur': 'Bhogpur',
  'bholath': 'Bholath',
  'bhongir': 'Bhongir',
  'bhopal': 'Bhopal',
  'bhowali': 'Bhowali',
  'bhubaneswar': 'Bhubaneswar',
  'bhucho-mandi': 'Bhucho Mandi',
  'bhuj': 'Bhuj',
  'bhusawal': 'Bhusawal',
  'bhuvanagiri': 'Bhuvanagiri',
  'bicholim': 'Bicholim',
  'bidar': 'Bidar',
  'bihar-sharif': 'Bihar Sharif',
  'biharsharif': 'Biharsharif',
  'bijapur': 'Bijapur',
  'bijnor': 'Bijnor',
  'bikaner': 'Bikaner',
  'bikramganj': 'Bikramganj',
  'bilaspur': 'Bilaspur',
  'bilga': 'Bilga',
  'bilsanda': 'Bilsanda',
  'bina': 'Bina',
  'biridi': 'Biridi',
  'bisalpur': 'Bisalpur',
  'bishnupur': 'Bishnupur',
  'bissam-cuttack': 'Bissam Cuttack',
  'bistupur': 'Bistupur',
  'boath': 'Boath',
  'boden': 'Boden',
  'bodh-gaya': 'Bodh Gaya',
  'boduppal': 'Boduppal',
  'boipariguda': 'Boipariguda',
  'boisar': 'Boisar',
  'bokaro': 'Bokaro',
  'bolpur': 'Bolpur',
  'bomdila': 'Bomdila',
  'bonakal': 'Bonakal',
  'bongaigaon': 'Bongaigaon',
  'borigumma': 'Borigumma',
  'borsad': 'Borsad',
  'botad': 'Botad',
  'brahmagiri': 'Brahmagiri',
  'brahmapur': 'Brahmapur',
  'brahmavar': 'Brahmavar',
  'budaun': 'Budaun',
  'budge-budge': 'Budge Budge',
  'bulandshahr': 'Bulandshahr',
  'bundi': 'Bundi',
  'burgampahad': 'Burgampahad',
  'burhanpur': 'Burhanpur',
  'buxar': 'Buxar',
  'byadgi': 'Byadgi',
  'byndoor': 'Byndoor',
  'canning': 'Canning',
  'car-nicobar': 'Car Nicobar',
  'central-delhi': 'Central Delhi',
  'chaibasa': 'Chaibasa',
  'chakdaha': 'Chakdaha',
  'chakia': 'Chakia',
  'chalakudy': 'Chalakudy',
  'challakere': 'Challakere',
  'chamarajanagar': 'Chamarajanagar',
  'chamba': 'Chamba',
  'chamoli': 'Chamoli',
  'champa': 'Champa',
  'champadanga': 'Champadanga',
  'champawat': 'Champawat',
  'champhai': 'Champhai',
  'chandabali': 'Chandabali',
  'chandahandi': 'Chandahandi',
  'chandannagar': 'Chandannagar',
  'chandauli': 'Chandauli',
  'chandausi': 'Chandausi',
  'chandigarh': 'Chandigarh',
  'chandili': 'Chandili',
  'chandipur': 'Chandipur',
  'chandrapur': 'Chandrapur',
  'chandrugonda': 'Chandrugonda',
  'chandur': 'Chandur',
  'changanassery': 'Changanassery',
  'channagiri': 'Channagiri',
  'channapatna': 'Channapatna',
  'channarayapatna': 'Channarayapatna',
  'chas': 'Chas',
  'chatra': 'Chatra',
  'chavakkad': 'Chavakkad',
  'chengalpattu': 'Chengalpattu',
  'chengannur': 'Chengannur',
  'chennai': 'Chennai',
  'chennur': 'Chennur',
  'cherla': 'Cherla',
  'cherpulassery': 'Cherpulassery',
  'cherthala': 'Cherthala',
  'cheyyar': 'Cheyyar',
  'cheyyur': 'Cheyyur',
  'chhachhrauli': 'Chhachhrauli',
  'chhapra': 'Chhapra',
  'chhatarpur': 'Chhatarpur',
  'chhatna': 'Chhatna',
  'chhindwara': 'Chhindwara',
  'chhota-udaipur': 'Chhota Udaipur',
  'chikballapur': 'Chikballapur',
  'chikhli': 'Chikhli',
  'chikkanayakanahalli': 'Chikkanayakanahalli',
  'chikmagalur': 'Chikmagalur',
  'chikodi': 'Chikodi',
  'chilakaluripet': 'Chilakaluripet',
  'chillupar': 'Chillupar',
  'chincholi': 'Chincholi',
  'chinnasalem': 'Chinnasalem',
  'chinsurah': 'Chinsurah',
  'chintamani': 'Chintamani',
  'chinyalisaur': 'Chinyalisaur',
  'chiplun': 'Chiplun',
  'chirala': 'Chirala',
  'chirayinkeezhu': 'Chirayinkeezhu',
  'chitapur': 'Chitapur',
  'chitradurga': 'Chitradurga',
  'chitrakonda': 'Chitrakonda',
  'chittoor': 'Chittoor',
  'chittorgarh': 'Chittorgarh',
  'chittur': 'Chittur',
  'chopan': 'Chopan',
  'choutuppal': 'Choutuppal',
  'chrompet': 'Chrompet',
  'churachandpur': 'Churachandpur',
  'churk': 'Churk',
  'churu': 'Churu',
  'coimbatore': 'Coimbatore',
  'contai': 'Contai',
  'cooch-behar': 'Cooch Behar',
  'cuddalore': 'Cuddalore',
  'cuttack': 'Cuttack',
  'dabhoi': 'Dabhoi',
  'dabugam': 'Dabugam',
  'dabwali': 'Dabwali',
  'dahanu': 'Dahanu',
  'dahegam': 'Dahegam',
  'dahod': 'Dahod',
  'daman': 'Daman',
  'dameracherla': 'Dameracherla',
  'damoh': 'Damoh',
  'danapur': 'Danapur',
  'dankuni': 'Dankuni',
  'dantewada': 'Dantewada',
  'dapoli': 'Dapoli',
  'darbhanga': 'Darbhanga',
  'darjeeling': 'Darjeeling',
  'darwha': 'Darwha',
  'dasmantpur': 'Dasmantpur',
  'dasuya': 'Dasuya',
  'datia': 'Datia',
  'dausa': 'Dausa',
  'davanagere': 'Davanagere',
  'davangere': 'Davangere',
  'deeg': 'Deeg',
  'deesa': 'Deesa',
  'dehlon': 'Dehlon',
  'dehradun': 'Dehradun',
  'dehri': 'Dehri',
  'delang': 'Delang',
  'delhi': 'Delhi',
  'deoghar': 'Deoghar',
  'deori': 'Deori',
  'deoria': 'Deoria',
  'dera-baba-nanak': 'Dera Baba Nanak',
  'deulgaon-raja': 'Deulgaon Raja',
  'devadurga': 'Devadurga',
  'devanahalli': 'Devanahalli',
  'devarakonda': 'Devarakonda',
  'devprayag': 'Devprayag',
  'devrukh': 'Devrukh',
  'dewas': 'Dewas',
  'dhamnagar': 'Dhamnagar',
  'dhamtari': 'Dhamtari',
  'dhanaulti': 'Dhanaulti',
  'dhanbad': 'Dhanbad',
  'dhaniakhali': 'Dhaniakhali',
  'dharamgarh': 'Dharamgarh',
  'dharamkot': 'Dharamkot',
  'dharamshala': 'Dharamshala',
  'dharchula': 'Dharchula',
  'dharmanagar': 'Dharmanagar',
  'dharmapuri': 'Dharmapuri',
  'dharmavaram': 'Dharmavaram',
  'dharwad': 'Dharwad',
  'dhaulpur': 'Dhaulpur',
  'dhenkanal': 'Dhenkanal',
  'dhilwan': 'Dhilwan',
  'dholka': 'Dholka',
  'dholpur': 'Dholpur',
  'dhoraji': 'Dhoraji',
  'dhubri': 'Dhubri',
  'dhule': 'Dhule',
  'dhulian': 'Dhulian',
  'dhuri': 'Dhuri',
  'diamond-harbour': 'Diamond Harbour',
  'dibrugarh': 'Dibrugarh',
  'didihat': 'Didihat',
  'digras': 'Digras',
  'dimapur': 'Dimapur',
  'dinanagar': 'Dinanagar',
  'dindigul': 'Dindigul',
  'dindori': 'Dindori',
  'diphu': 'Diphu',
  'dirba': 'Dirba',
  'diu': 'Diu',
  'doddaballapur': 'Doddaballapur',
  'doiwala': 'Doiwala',
  'domjur': 'Domjur',
  'doraha': 'Doraha',
  'dornakal': 'Dornakal',
  'dronagiri': 'Dronagiri',
  'duddhi': 'Duddhi',
  'dugadda': 'Dugadda',
  'dumka': 'Dumka',
  'dummagudem': 'Dummagudem',
  'dunda': 'Dunda',
  'dungarpur': 'Dungarpur',
  'durg': 'Durg',
  'durgapur': 'Durgapur',
  'dwarahat': 'Dwarahat',
  'dwarka': 'Dwarka',
  'east-delhi': 'East Delhi',
  'edappadi': 'Edappadi',
  'ellenabad': 'Ellenabad',
  'eluru': 'Eluru',
  'enkoor': 'Enkoor',
  'erode': 'Erode',
  'ersama': 'Ersama',
  'etah': 'Etah',
  'etawah': 'Etawah',
  'ettumanoor': 'Ettumanoor',
  'faizabad': 'Faizabad',
  'falta': 'Falta',
  'faridabad': 'Faridabad',
  'faridkot': 'Faridkot',
  'farrukhabad': 'Farrukhabad',
  'fatehabad': 'Fatehabad',
  'fatehgarh-churian': 'Fatehgarh Churian',
  'fatehgarh-sahib': 'Fatehgarh Sahib',
  'fatehpur': 'Fatehpur',
  'fazilka': 'Fazilka',
  'fazilnagar': 'Fazilnagar',
  'ferozepur-cantt': 'Ferozepur Cantt',
  'ferozepur-jhirka': 'Ferozepur Jhirka',
  'firozabad': 'Firozabad',
  'firozpur': 'Firozpur',
  'forbesganj': 'Forbesganj',
  'gadag': 'Gadag',
  'gadarpur': 'Gadarpur',
  'gadarwara': 'Gadarwara',
  'gainsari': 'Gainsari',
  'gairsain': 'Gairsain',
  'gandhidham': 'Gandhidham',
  'gandhinagar': 'Gandhinagar',
  'gangajalghati': 'Gangajalghati',
  'gangapur-city': 'Gangapur City',
  'gangavalli': 'Gangavalli',
  'gangavathi': 'Gangavathi',
  'gangolihat': 'Gangolihat',
  'gangotri': 'Gangotri',
  'gangtok': 'Gangtok',
  'garhshankar': 'Garhshankar',
  'garhwa': 'Garhwa',
  'gariaband': 'Gariaband',
  'gauribidanur': 'Gauribidanur',
  'gaya': 'Gaya',
  'gayeshpur': 'Gayeshpur',
  'ghanaur': 'Ghanaur',
  'ghansali': 'Ghansali',
  'gharaunda': 'Gharaunda',
  'ghatkesar': 'Ghatkesar',
  'ghaziabad': 'Ghaziabad',
  'ghazipur': 'Ghazipur',
  'ghosi': 'Ghosi',
  'gidderbaha': 'Gidderbaha',
  'gill': 'Gill',
  'gingee': 'Gingee',
  'giridih': 'Giridih',
  'gobindgarh': 'Gobindgarh',
  'godda': 'Godda',
  'godhra': 'Godhra',
  'goghat': 'Goghat',
  'gohad': 'Gohad',
  'gohana': 'Gohana',
  'goindwal-sahib': 'Goindwal Sahib',
  'gokak': 'Gokak',
  'gonda': 'Gonda',
  'gondal': 'Gondal',
  'gondia': 'Gondia',
  'goniana': 'Goniana',
  'gop': 'Gop',
  'gopalganj': 'Gopalganj',
  'gorakhpur': 'Gorakhpur',
  'goraya': 'Goraya',
  'govindgarh': 'Govindgarh',
  'govindpur': 'Govindpur',
  'greater-noida': 'Greater Noida',
  'gubbi': 'Gubbi',
  'gudari': 'Gudari',
  'gudivada': 'Gudivada',
  'gudiyattam': 'Gudiyattam',
  'guduvancheri': 'Guduvancheri',
  'guhagar': 'Guhagar',
  'guindy': 'Guindy',
  'gulbarga': 'Gulbarga',
  'guledgudda': 'Guledgudda',
  'gumla': 'Gumla',
  'gummidipoondi': 'Gummidipoondi',
  'guna': 'Guna',
  'gundala': 'Gundala',
  'gundlupet': 'Gundlupet',
  'guntakal': 'Guntakal',
  'guntur': 'Guntur',
  'gunupur': 'Gunupur',
  'gurdaspur': 'Gurdaspur',
  'guru-har-sahai': 'Guru Har Sahai',
  'gurugram': 'Gurugram',
  'guruvayoor': 'Guruvayoor',
  'guwahati': 'Guwahati',
  'gwalior': 'Gwalior',
  'gyalshing': 'Gyalshing',
  'gyanpur': 'Gyanpur',
  'h-d-kote': 'H D Kote',
  'habra': 'Habra',
  'hajipur': 'Hajipur',
  'haldia': 'Haldia',
  'haldwani': 'Haldwani',
  'haliya': 'Haliya',
  'halol': 'Halol',
  'hamirpur': 'Hamirpur',
  'hansi': 'Hansi',
  'hanumangarh': 'Hanumangarh',
  'hapur': 'Hapur',
  'hardoi': 'Hardoi',
  'hariana': 'Hariana',
  'haridwar': 'Haridwar',
  'harihar': 'Harihar',
  'haripad': 'Haripad',
  'haripal': 'Haripal',
  'harur': 'Harur',
  'hassan': 'Hassan',
  'hata': 'Hata',
  'hathiundha': 'Hathiundha',
  'hathras': 'Hathras',
  'haveri': 'Haveri',
  'hayathnagar': 'Hayathnagar',
  'hazaribagh': 'Hazaribagh',
  'herbertpur': 'Herbertpur',
  'himatnagar': 'Himatnagar',
  'hindaun': 'Hindaun',
  'hindupur': 'Hindupur',
  'hinganghat': 'Hinganghat',
  'hingna': 'Hingna',
  'hirbandh': 'Hirbandh',
  'hirekerur': 'Hirekerur',
  'hisar': 'Hisar',
  'hodal': 'Hodal',
  'holalkere': 'Holalkere',
  'holenarasipur': 'Holenarasipur',
  'honnali': 'Honnali',
  'hooghly': 'Hooghly',
  'hosadurga': 'Hosadurga',
  'hosakote': 'Hosakote',
  'hosdurg': 'Hosdurg',
  'hoshangabad': 'Hoshangabad',
  'hoshiarpur': 'Hoshiarpur',
  'hospet': 'Hospet',
  'hosur': 'Hosur',
  'howrah': 'Howrah',
  'hubli': 'Hubli',
  'hukkeri': 'Hukkeri',
  'humnabad': 'Humnabad',
  'hungund': 'Hungund',
  'hunsur': 'Hunsur',
  'hura': 'Hura',
  'hussainiwala': 'Hussainiwala',
  'huzurnagar': 'Huzurnagar',
  'hyderabad': 'Hyderabad',
  'ichalkaranji': 'Ichalkaranji',
  'ichoda': 'Ichoda',
  'idar': 'Idar',
  'ikauna': 'Ikauna',
  'ilkal': 'Ilkal',
  'imphal': 'Imphal',
  'indas': 'Indas',
  'indi': 'Indi',
  'indore': 'Indore',
  'indravelly': 'Indravelly',
  'irinjalakuda': 'Irinjalakuda',
  'iritty': 'Iritty',
  'itanagar': 'Itanagar',
  'itarsi': 'Itarsi',
  'jabalpur': 'Jabalpur',
  'jagadhri': 'Jagadhri',
  'jagalur': 'Jagalur',
  'jagatballavpur': 'Jagatballavpur',
  'jagatsinghpur': 'Jagatsinghpur',
  'jagdalpur': 'Jagdalpur',
  'jagraon': 'Jagraon',
  'jagtial': 'Jagtial',
  'jahanabad': 'Jahanabad',
  'jainad': 'Jainad',
  'jainoor': 'Jainoor',
  'jaipatna': 'Jaipatna',
  'jaipur': 'Jaipur',
  'jajpur': 'Jajpur',
  'jalalabad': 'Jalalabad',
  'jalandhar': 'Jalandhar',
  'jaleswar': 'Jaleswar',
  'jalgaon': 'Jalgaon',
  'jalna': 'Jalna',
  'jalpaiguri': 'Jalpaiguri',
  'jamkhandi': 'Jamkhandi',
  'jammu': 'Jammu',
  'jamnagar': 'Jamnagar',
  'jamshedpur': 'Jamshedpur',
  'jamtara': 'Jamtara',
  'jamui': 'Jamui',
  'jandiala-guru': 'Jandiala Guru',
  'jangaon': 'Jangaon',
  'jangipur': 'Jangipur',
  'janjgir': 'Janjgir',
  'jannaram': 'Jannaram',
  'jarwal': 'Jarwal',
  'jaspur': 'Jaspur',
  'jatara': 'Jatara',
  'jaunpur': 'Jaunpur',
  'jawhar': 'Jawhar',
  'jaynagar': 'Jaynagar',
  'jaypur': 'Jaypur',
  'jehanabad': 'Jehanabad',
  'jetpur': 'Jetpur',
  'jeypore': 'Jeypore',
  'jhabrera': 'Jhabrera',
  'jhalda': 'Jhalda',
  'jhansi': 'Jhansi',
  'jharigam': 'Jharigam',
  'jharsuguda': 'Jharsuguda',
  'jhunjhunu': 'Jhunjhunu',
  'jind': 'Jind',
  'jirat': 'Jirat',
  'jodhpur': 'Jodhpur',
  'jorhat': 'Jorhat',
  'joshimath': 'Joshimath',
  'joura': 'Joura',
  'jowai': 'Jowai',
  'joynagar': 'Joynagar',
  'joypur': 'Joypur',
  'jugsalai': 'Jugsalai',
  'julurupadu': 'Julurupadu',
  'junagadh': 'Junagadh',
  'junagarh': 'Junagarh',
  'kadapa': 'Kadapa',
  'kadi': 'Kadi',
  'kadma': 'Kadma',
  'kadur': 'Kadur',
  'kagaznagar': 'Kagaznagar',
  'kailaras': 'Kailaras',
  'kailashahar': 'Kailashahar',
  'kaisarganj': 'Kaisarganj',
  'kaithal': 'Kaithal',
  'kakatpur': 'Kakatpur',
  'kakching': 'Kakching',
  'kakdwip': 'Kakdwip',
  'kakinada': 'Kakinada',
  'kalahandi': 'Kalahandi',
  'kalampur': 'Kalampur',
  'kalanaur': 'Kalanaur',
  'kalayat': 'Kalayat',
  'kalimela': 'Kalimela',
  'kalka': 'Kalka',
  'kallakurichi': 'Kallakurichi',
  'kallur': 'Kallur',
  'kalmeshwar': 'Kalmeshwar',
  'kalol': 'Kalol',
  'kalpakkam': 'Kalpakkam',
  'kalpetta': 'Kalpetta',
  'kalyan-dombivali': 'Kalyan-Dombivali',
  'kalyani': 'Kalyani',
  'kalyansinghpur': 'Kalyansinghpur',
  'kamarhati': 'Kamarhati',
  'kamothe': 'Kamothe',
  'kamptee': 'Kamptee',
  'kanakapura': 'Kanakapura',
  'kanas': 'Kanas',
  'kanchipuram': 'Kanchipuram',
  'kanchrapara': 'Kanchrapara',
  'kanhangad': 'Kanhangad',
  'kankavli': 'Kankavli',
  'kanker': 'Kanker',
  'kannur': 'Kannur',
  'kanpur': 'Kanpur',
  'kapkot': 'Kapkot',
  'kapra': 'Kapra',
  'kaptanganj': 'Kaptanganj',
  'kapurthala': 'Kapurthala',
  'karad': 'Karad',
  'karahal': 'Karahal',
  'karaikal': 'Karaikal',
  'karaikkudi': 'Karaikkudi',
  'karanja-lad': 'Karanja Lad',
  'karauli': 'Karauli',
  'kargil': 'Kargil',
  'karimnagar': 'Karimnagar',
  'karjat': 'Karjat',
  'karkala': 'Karkala',
  'karnal': 'Karnal',
  'karnaprayag': 'Karnaprayag',
  'kartarpur': 'Kartarpur',
  'karunagappally': 'Karunagappally',
  'karur': 'Karur',
  'kasaragod': 'Kasaragod',
  'kasganj': 'Kasganj',
  'kashipur': 'Kashipur',
  'kasia': 'Kasia',
  'kathua': 'Kathua',
  'kathumar': 'Kathumar',
  'katihar': 'Katihar',
  'katni': 'Katni',
  'katol': 'Katol',
  'katra': 'Katra',
  'katra-bazar': 'Katra Bazar',
  'kausani': 'Kausani',
  'kavali': 'Kavali',
  'kavaratti': 'Kavaratti',
  'kaveripakkam': 'Kaveripakkam',
  'kawardha': 'Kawardha',
  'kayamkulam': 'Kayamkulam',
  'kedarnath': 'Kedarnath',
  'keesara': 'Keesara',
  'kelambakkam': 'Kelambakkam',
  'kendrapara': 'Kendrapara',
  'kendujhar': 'Kendujhar',
  'keonjhar': 'Keonjhar',
  'kerakat': 'Kerakat',
  'kerimeri': 'Kerimeri',
  'kesamudram': 'Kesamudram',
  'keshod': 'Keshod',
  'kesinga': 'Kesinga',
  'khadda': 'Khadda',
  'khadur-sahib': 'Khadur Sahib',
  'khagaria': 'Khagaria',
  'khalilabad': 'Khalilabad',
  'khamanon': 'Khamanon',
  'khambhat': 'Khambhat',
  'khamgaon': 'Khamgaon',
  'khammam': 'Khammam',
  'khanakul': 'Khanakul',
  'khandwa': 'Khandwa',
  'khanna': 'Khanna',
  'kharagpur': 'Kharagpur',
  'kharar': 'Kharar',
  'kharghar': 'Kharghar',
  'khargone': 'Khargone',
  'khariar': 'Khariar',
  'khatima': 'Khatima',
  'khatra': 'Khatra',
  'khed': 'Khed',
  'kheda': 'Kheda',
  'khesraha': 'Khesraha',
  'khopoli': 'Khopoli',
  'khurai': 'Khurai',
  'khurja': 'Khurja',
  'kichha': 'Kichha',
  'kilimanoor': 'Kilimanoor',
  'kishanganj': 'Kishanganj',
  'kishangarh': 'Kishangarh',
  'kishangarh-bas': 'Kishangarh Bas',
  'kochi': 'Kochi',
  'kodad': 'Kodad',
  'kodambakkam': 'Kodambakkam',
  'koderma': 'Koderma',
  'kodungallur': 'Kodungallur',
  'kohima': 'Kohima',
  'kolar': 'Kolar',
  'kolasib': 'Kolasib',
  'kolhapur': 'Kolhapur',
  'kolkata': 'Kolkata',
  'kollam': 'Kollam',
  'kollegal': 'Kollegal',
  'kolli-hills': 'Kolli Hills',
  'kolnara': 'Kolnara',
  'komna': 'Komna',
  'kompally': 'Kompally',
  'konark': 'Konark',
  'kondagaon': 'Kondagaon',
  'kondotty': 'Kondotty',
  'kopaganj': 'Kopaganj',
  'koppa': 'Koppa',
  'koppal': 'Koppal',
  'koraput': 'Koraput',
  'koratagere': 'Koratagere',
  'korba': 'Korba',
  'korukonda': 'Korukonda',
  'kosagumuda': 'Kosagumuda',
  'kota': 'Kota',
  'kotdwar': 'Kotdwar',
  'kothagudem': 'Kothagudem',
  'kothamangalam': 'Kothamangalam',
  'kotkapura': 'Kotkapura',
  'kotkasim': 'Kotkasim',
  'kotpad': 'Kotpad',
  'kottarakkara': 'Kottarakkara',
  'kottayam': 'Kottayam',
  'kotulpur': 'Kotulpur',
  'koyilandy': 'Koyilandy',
  'kozhikode': 'Kozhikode',
  'krishnagiri': 'Krishnagiri',
  'krishnanagar': 'Krishnanagar',
  'krishnarajanagara': 'Krishnarajanagara',
  'krushnaprasad': 'Krushnaprasad',
  'kudal': 'Kudal',
  'kudumuluguma': 'Kudumuluguma',
  'kuhi': 'Kuhi',
  'kujang': 'Kujang',
  'kukatpally': 'Kukatpally',
  'kullu': 'Kullu',
  'kultali': 'Kultali',
  'kumarapalayam': 'Kumarapalayam',
  'kumbakonam': 'Kumbakonam',
  'kumher': 'Kumher',
  'kundapura': 'Kundapura',
  'kundrathur': 'Kundrathur',
  'kunigal': 'Kunigal',
  'kunnamkulam': 'Kunnamkulam',
  'kuravi': 'Kuravi',
  'kurnool': 'Kurnool',
  'kushtagi': 'Kushtagi',
  'kusumanchi': 'Kusumanchi',
  'kuthuparamba': 'Kuthuparamba',
  'kuttanad': 'Kuttanad',
  'kyathampalli': 'Kyathampalli',
  'ladwa': 'Ladwa',
  'lahar': 'Lahar',
  'lakhimpur': 'Lakhimpur',
  'lakhisarai': 'Lakhisarai',
  'laksar': 'Laksar',
  'lalitpur': 'Lalitpur',
  'lambi': 'Lambi',
  'lamtaput': 'Lamtaput',
  'landhaura': 'Landhaura',
  'lanja': 'Lanja',
  'lanjigarh': 'Lanjigarh',
  'lansdowne': 'Lansdowne',
  'latehar': 'Latehar',
  'latur': 'Latur',
  'laundi': 'Laundi',
  'laxmangarh': 'Laxmangarh',
  'laxmipur': 'Laxmipur',
  'lb-nagar': 'LB Nagar',
  'leh': 'Leh',
  'lehragaga': 'Lehragaga',
  'lingasugur': 'Lingasugur',
  'lohaghat': 'Lohaghat',
  'lohardaga': 'Lohardaga',
  'lohian-khas': 'Lohian Khas',
  'lonar': 'Lonar',
  'longowal': 'Longowal',
  'lucknow': 'Lucknow',
  'ludhiana': 'Ludhiana',
  'lunawada': 'Lunawada',
  'lunglei': 'Lunglei',
  'luxettipet': 'Luxettipet',
  'machhali-shahar': 'Machhali Shahar',
  'machhiwara': 'Machhiwara',
  'machilipatnam': 'Machilipatnam',
  'madanapalle': 'Madanapalle',
  'madhavaram': 'Madhavaram',
  'madhira': 'Madhira',
  'madhubani': 'Madhubani',
  'madhugiri': 'Madhugiri',
  'madhupur': 'Madhupur',
  'madurai': 'Madurai',
  'madurantakam': 'Madurantakam',
  'magadi': 'Magadi',
  'magrahat': 'Magrahat',
  'mahabaleshwar': 'Mahabaleshwar',
  'mahabubabad': 'Mahabubabad',
  'mahad': 'Mahad',
  'maharajpur': 'Maharajpur',
  'mahasamund': 'Mahasamund',
  'mahbubnagar': 'Mahbubnagar',
  'mahe': 'Mahe',
  'mahsi': 'Mahsi',
  'mahuva': 'Mahuva',
  'maihar': 'Maihar',
  'mailam': 'Mailam',
  'mainpuri': 'Mainpuri',
  'majitha': 'Majitha',
  'makhu': 'Makhu',
  'makrana': 'Makrana',
  'malakhera': 'Malakhera',
  'malappuram': 'Malappuram',
  'malda': 'Malda',
  'malegaon': 'Malegaon',
  'malerkotla': 'Malerkotla',
  'malhani': 'Malhani',
  'malkajgiri': 'Malkajgiri',
  'malkangiri': 'Malkangiri',
  'malout': 'Malout',
  'malthone': 'Malthone',
  'malur': 'Malur',
  'malvan': 'Malvan',
  'mamallapuram': 'Mamallapuram',
  'mamdot': 'Mamdot',
  'manali': 'Manali',
  'mananthavady': 'Mananthavady',
  'manavadar': 'Manavadar',
  'manbazar': 'Manbazar',
  'mancherial': 'Mancherial',
  'mandamarri': 'Mandamarri',
  'mandangad': 'Mandangad',
  'mandi': 'Mandi',
  'mandla': 'Mandla',
  'mandsaur': 'Mandsaur',
  'mandvi': 'Mandvi',
  'mandya': 'Mandya',
  'mangalagiri': 'Mangalagiri',
  'mangalore': 'Mangalore',
  'mangan': 'Mangan',
  'mangaon': 'Mangaon',
  'manglaur': 'Manglaur',
  'mango': 'Mango',
  'mangrol': 'Mangrol',
  'mangrulpir': 'Mangrulpir',
  'manipal': 'Manipal',
  'manjeri': 'Manjeri',
  'mankapur': 'Mankapur',
  'mannarkad': 'Mannarkad',
  'manora': 'Manora',
  'mansa': 'Mansa',
  'manuguru': 'Manuguru',
  'manvi': 'Manvi',
  'mapusa': 'Mapusa',
  'marakkanam': 'Marakkanam',
  'margao': 'Margao',
  'mariahu': 'Mariahu',
  'maripeda': 'Maripeda',
  'markapur': 'Markapur',
  'marshaghai': 'Marshaghai',
  'mathili': 'Mathili',
  'mathura': 'Mathura',
  'mathurapur': 'Mathurapur',
  'mattannur': 'Mattannur',
  'mau': 'Mau',
  'maunath-bhanjan': 'Maunath Bhanjan',
  'maur-mandi': 'Maur Mandi',
  'mavelikara': 'Mavelikara',
  'mayurbhanj': 'Mayurbhanj',
  'medavakkam': 'Medavakkam',
  'medchal': 'Medchal',
  'medininagar': 'Medininagar',
  'medinipur': 'Medinipur',
  'meerpet': 'Meerpet',
  'meerut': 'Meerut',
  'mehatpur': 'Mehatpur',
  'mehgaon': 'Mehgaon',
  'mehkar': 'Mehkar',
  'mehsana': 'Mehsana',
  'mejia': 'Mejia',
  'melmalaiyanur': 'Melmalaiyanur',
  'melmaruvathur': 'Melmaruvathur',
  'menhdawal': 'Menhdawal',
  'mettur': 'Mettur',
  'mhasla': 'Mhasla',
  'midnapore': 'Midnapore',
  'minicoy': 'Minicoy',
  'mira-bhayandar': 'Mira-Bhayandar',
  'miraj': 'Miraj',
  'miryalaguda': 'Miryalaguda',
  'miryalguda': 'Miryalguda',
  'mirzapur': 'Mirzapur',
  'miyapur': 'Miyapur',
  'modasa': 'Modasa',
  'modinagar': 'Modinagar',
  'moga': 'Moga',
  'mogra': 'Mogra',
  'mohali': 'Mohali',
  'mohammadabad': 'Mohammadabad',
  'mohgaon': 'Mohgaon',
  'mohpa': 'Mohpa',
  'mokama': 'Mokama',
  'mokhada': 'Mokhada',
  'mokokchung': 'Mokokchung',
  'molakalmuru': 'Molakalmuru',
  'moonak': 'Moonak',
  'moradabad': 'Moradabad',
  'morappur': 'Morappur',
  'morbi': 'Morbi',
  'morena': 'Morena',
  'mori': 'Mori',
  'morinda': 'Morinda',
  'mothkur': 'Mothkur',
  'motihari': 'Motihari',
  'mouda': 'Mouda',
  'muddebihal': 'Muddebihal',
  'mudgal': 'Mudgal',
  'mudhol': 'Mudhol',
  'mudigere': 'Mudigere',
  'mughalsarai': 'Mughalsarai',
  'muhammadabad-gohna': 'Muhammadabad Gohna',
  'mukerian': 'Mukerian',
  'mukteshwar': 'Mukteshwar',
  'muktsar': 'Muktsar',
  'mulakalapalli': 'Mulakalapalli',
  'mulbagal': 'Mulbagal',
  'mullanpur-dakha': 'Mullanpur Dakha',
  'multai': 'Multai',
  'mumbai': 'Mumbai',
  'mundargi': 'Mundargi',
  'mundawar': 'Mundawar',
  'mungeli': 'Mungeli',
  'munger': 'Munger',
  'mungra-badshahpur': 'Mungra Badshahpur',
  'muniguda': 'Muniguda',
  'munsyari': 'Munsyari',
  'munugode': 'Munugode',
  'murud': 'Murud',
  'murwara': 'Murwara',
  'mussoorie': 'Mussoorie',
  'muvattupuzha': 'Muvattupuzha',
  'muzaffarnagar': 'Muzaffarnagar',
  'muzaffarpur': 'Muzaffarpur',
  'myorpur': 'Myorpur',
  'mysore': 'Mysore',
  'nabadwip': 'Nabadwip',
  'nabha': 'Nabha',
  'nabrangpur': 'Nabrangpur',
  'nacharam': 'Nacharam',
  'nadbai': 'Nadbai',
  'nadiad': 'Nadiad',
  'nagal': 'Nagal',
  'nagaon': 'Nagaon',
  'nagapattinam': 'Nagapattinam',
  'nagar': 'Nagar',
  'nagarjunasagar': 'Nagarjunasagar',
  'nagaur': 'Nagaur',
  'nagda': 'Nagda',
  'nagercoil': 'Nagercoil',
  'nagod': 'Nagod',
  'nagole': 'Nagole',
  'nagpur': 'Nagpur',
  'nagpur-rural': 'Nagpur Rural',
  'nagwa': 'Nagwa',
  'nahan': 'Nahan',
  'naharlagun': 'Naharlagun',
  'naihati': 'Naihati',
  'nainital': 'Nainital',
  'nakhatrana': 'Nakhatrana',
  'nakodar': 'Nakodar',
  'nakrekal': 'Nakrekal',
  'nalanda': 'Nalanda',
  'nalasopara': 'Nalasopara',
  'nalgonda': 'Nalgonda',
  'namakkal': 'Namakkal',
  'namchi': 'Namchi',
  'namkhana': 'Namkhana',
  'nandapur': 'Nandapur',
  'nandura': 'Nandura',
  'nandurbar': 'Nandurbar',
  'nandyal': 'Nandyal',
  'nangal': 'Nangal',
  'nanjangud': 'Nanjangud',
  'narasapuram': 'Narasapuram',
  'narasaraopet': 'Narasaraopet',
  'narasimharajapura': 'Narasimharajapura',
  'narayanpatna': 'Narayanpatna',
  'narayanpur': 'Narayanpur',
  'narendranagar': 'Narendranagar',
  'nargund': 'Nargund',
  'narketpally': 'Narketpally',
  'narkhed': 'Narkhed',
  'narla': 'Narla',
  'narmadapuram': 'Narmadapuram',
  'narnaul': 'Narnaul',
  'narnaund': 'Narnaund',
  'narnoor': 'Narnoor',
  'narsampet': 'Narsampet',
  'narsinghpur': 'Narsinghpur',
  'narwana': 'Narwana',
  'nashik': 'Nashik',
  'nathana': 'Nathana',
  'nathdwara': 'Nathdwara',
  'natrampalli': 'Natrampalli',
  'naugachhia': 'Naugachhia',
  'nautanwa': 'Nautanwa',
  'navi-mumbai': 'Navi Mumbai',
  'navsari': 'Navsari',
  'nawabganj': 'Nawabganj',
  'nawada': 'Nawada',
  'nawanshahr': 'Nawanshahr',
  'nedumangad': 'Nedumangad',
  'neemrana': 'Neemrana',
  'neemuch': 'Neemuch',
  'nekkonda': 'Nekkonda',
  'nelamangala': 'Nelamangala',
  'nellikuduru': 'Nellikuduru',
  'nellore': 'Nellore',
  'nemmara': 'Nemmara',
  'nennal': 'Nennal',
  'neturia': 'Neturia',
  'new-delhi': 'New Delhi',
  'new-tehri': 'New Tehri',
  'neyveli': 'Neyveli',
  'neyyattinkara': 'Neyyattinkara',
  'nhava-sheva': 'Nhava Sheva',
  'nihal-singh-wala': 'Nihal Singh Wala',
  'nilagiri': 'Nilagiri',
  'nimapara': 'Nimapara',
  'nimbahera': 'Nimbahera',
  'nirmal': 'Nirmal',
  'nischintakoili': 'Nischintakoili',
  'niwari': 'Niwari',
  'nizamabad': 'Nizamabad',
  'noida': 'Noida',
  'nongstoin': 'Nongstoin',
  'north-delhi': 'North Delhi',
  'nuapada': 'Nuapada',
  'nuh': 'Nuh',
  'nurmahal': 'Nurmahal',
  'obra': 'Obra',
  'omalur': 'Omalur',
  'onda': 'Onda',
  'ongole': 'Ongole',
  'oragadam': 'Oragadam',
  'orai': 'Orai',
  'orchha': 'Orchha',
  'osmanabad': 'Osmanabad',
  'ottapalam': 'Ottapalam',
  'pachmarhi': 'Pachmarhi',
  'pachperwa': 'Pachperwa',
  'padampur': 'Padampur',
  'padia': 'Padia',
  'padrauna': 'Padrauna',
  'pahari': 'Pahari',
  'pakhowal': 'Pakhowal',
  'pakur': 'Pakur',
  'pala': 'Pala',
  'palacode': 'Palacode',
  'palakkad': 'Palakkad',
  'palakollu': 'Palakollu',
  'palakurthy': 'Palakurthy',
  'palampur': 'Palampur',
  'palanpur': 'Palanpur',
  'palasa': 'Palasa',
  'palghar': 'Palghar',
  'pali': 'Pali',
  'palitana': 'Palitana',
  'pallavaram': 'Pallavaram',
  'palvancha': 'Palvancha',
  'palwal': 'Palwal',
  'pammal': 'Pammal',
  'panaji': 'Panaji',
  'panchgani': 'Panchgani',
  'panchkula': 'Panchkula',
  'panchla': 'Panchla',
  'pandalam': 'Pandalam',
  'pandhurna': 'Pandhurna',
  'pandua': 'Pandua',
  'panihati': 'Panihati',
  'panipat': 'Panipat',
  'panna': 'Panna',
  'pantnagar': 'Pantnagar',
  'panvel': 'Panvel',
  'paonta-sahib': 'Paonta Sahib',
  'papadahandi': 'Papadahandi',
  'para': 'Para',
  'paradip': 'Paradip',
  'paramathi': 'Paramathi',
  'parappanangadi': 'Parappanangadi',
  'paraswada': 'Paraswada',
  'parbhani': 'Parbhani',
  'parkal': 'Parkal',
  'parseoni': 'Parseoni',
  'pasighat': 'Pasighat',
  'patan': 'Patan',
  'pathanamthitta': 'Pathanamthitta',
  'pathankot': 'Pathankot',
  'patharpratima': 'Patharpratima',
  'pathri': 'Pathri',
  'patiala': 'Patiala',
  'patna': 'Patna',
  'patran': 'Patran',
  'patrasayer': 'Patrasayer',
  'pattambi': 'Pattambi',
  'pattamundai': 'Pattamundai',
  'patti': 'Patti',
  'pauri': 'Pauri',
  'pavagada': 'Pavagada',
  'payagpur': 'Payagpur',
  'payal': 'Payal',
  'payyannur': 'Payyannur',
  'payyanur': 'Payyanur',
  'peddavoora': 'Peddavoora',
  'peerzadiguda': 'Peerzadiguda',
  'pehowa': 'Pehowa',
  'pen': 'Pen',
  'pennagaram': 'Pennagaram',
  'penuballi': 'Penuballi',
  'perinthalmanna': 'Perinthalmanna',
  'periyapatna': 'Periyapatna',
  'pernambut': 'Pernambut',
  'perumbavoor': 'Perumbavoor',
  'perungudi': 'Perungudi',
  'petlad': 'Petlad',
  'phagwara': 'Phagwara',
  'phaltan': 'Phaltan',
  'pharenda': 'Pharenda',
  'phephna': 'Phephna',
  'phillaur': 'Phillaur',
  'phulwari-sharif': 'Phulwari Sharif',
  'phusro': 'Phusro',
  'pilibhit': 'Pilibhit',
  'pimpri-chinchwad': 'Pimpri-Chinchwad',
  'pinapaka': 'Pinapaka',
  'pinjore': 'Pinjore',
  'pipariya': 'Pipariya',
  'pipili': 'Pipili',
  'pipraich': 'Pipraich',
  'piravom': 'Piravom',
  'piriyapatna': 'Piriyapatna',
  'pithampur': 'Pithampur',
  'pithoragarh': 'Pithoragarh',
  'pochampalli': 'Pochampalli',
  'pocharam': 'Pocharam',
  'podia': 'Podia',
  'polba': 'Polba',
  'pollachi': 'Pollachi',
  'polur': 'Polur',
  'ponda': 'Ponda',
  'ponnani': 'Ponnani',
  'ponneri': 'Ponneri',
  'poonamallee': 'Poonamallee',
  'porbandar': 'Porbandar',
  'porsa': 'Porsa',
  'port-blair': 'Port Blair',
  'porur': 'Porur',
  'pottangi': 'Pottangi',
  'pratapgarh': 'Pratapgarh',
  'pratapnagar': 'Pratapnagar',
  'prayagraj': 'Prayagraj',
  'prithvipur': 'Prithvipur',
  'proddatur': 'Proddatur',
  'puducherry': 'Puducherry',
  'pulwama': 'Pulwama',
  'punalur': 'Punalur',
  'puncha': 'Puncha',
  'pundri': 'Pundri',
  'pune': 'Pune',
  'puranpur': 'Puranpur',
  'puri': 'Puri',
  'purnagiri': 'Purnagiri',
  'purnia': 'Purnia',
  'purola': 'Purola',
  'pursurah': 'Pursurah',
  'purulia': 'Purulia',
  'pusad': 'Pusad',
  'puttaparthi': 'Puttaparthi',
  'puttur': 'Puttur',
  'qadian': 'Qadian',
  'quthbullapur': 'Quthbullapur',
  'radaur': 'Radaur',
  'raebareli': 'Raebareli',
  'raghunathpally': 'Raghunathpally',
  'raghunathpur': 'Raghunathpur',
  'rahatgarh': 'Rahatgarh',
  'raibag': 'Raibag',
  'raichur': 'Raichur',
  'raiganj': 'Raiganj',
  'raigarh': 'Raigarh',
  'raighar': 'Raighar',
  'raikot': 'Raikot',
  'raipur': 'Raipur',
  'rajahmundry': 'Rajahmundry',
  'rajapalayam': 'Rajapalayam',
  'rajapur': 'Rajapur',
  'rajgarh': 'Rajgarh',
  'rajgir': 'Rajgir',
  'rajkanika': 'Rajkanika',
  'rajkot': 'Rajkot',
  'rajnagar': 'Rajnagar',
  'rajnandgaon': 'Rajnandgaon',
  'rajpur': 'Rajpur',
  'rajpura': 'Rajpura',
  'rajsamand': 'Rajsamand',
  'ramagundam': 'Ramagundam',
  'ramanagara': 'Ramanagara',
  'ramannapet': 'Ramannapet',
  'ramdurg': 'Ramdurg',
  'ramgarh': 'Ramgarh',
  'ramnagar': 'Ramnagar',
  'rampur': 'Rampur',
  'rampura-phul': 'Rampura Phul',
  'ramtek': 'Ramtek',
  'ranaghat': 'Ranaghat',
  'ranchi': 'Ranchi',
  'ranebennuru': 'Ranebennuru',
  'rangpo': 'Rangpo',
  'ranibandh': 'Ranibandh',
  'ranibennur': 'Ranibennur',
  'ranikhet': 'Ranikhet',
  'ranipet': 'Ranipet',
  'ranni': 'Ranni',
  'rapar': 'Rapar',
  'rasipuram': 'Rasipuram',
  'rasra': 'Rasra',
  'ratia': 'Ratia',
  'ratlam': 'Ratlam',
  'ratnagiri': 'Ratnagiri',
  'rayagada': 'Rayagada',
  'rayya': 'Rayya',
  'rebbena': 'Rebbena',
  'rehli': 'Rehli',
  'renukoot': 'Renukoot',
  'rewa': 'Rewa',
  'rewari': 'Rewari',
  'rishikesh': 'Rishikesh',
  'rishra': 'Rishra',
  'risod': 'Risod',
  'robertsganj': 'Robertsganj',
  'robertson-pet': 'Robertson Pet',
  'roha': 'Roha',
  'rohini': 'Rohini',
  'rohtak': 'Rohtak',
  'ron': 'Ron',
  'roorkee': 'Roorkee',
  'ropar': 'Ropar',
  'rosera': 'Rosera',
  'rourkela': 'Rourkela',
  'rudhauli': 'Rudhauli',
  'rudrapur': 'Rudrapur',
  'rupbas': 'Rupbas',
  'sabalgarh': 'Sabalgarh',
  'sadhaura': 'Sadhaura',
  'safidon': 'Safidon',
  'sagar': 'Sagar',
  'saharanpur': 'Saharanpur',
  'saharsa': 'Saharsa',
  'sahebganj': 'Sahebganj',
  'sahjanwa': 'Sahjanwa',
  'sahnewal': 'Sahnewal',
  'saidpur': 'Saidpur',
  'sakchi': 'Sakchi',
  'saket': 'Saket',
  'sakleshpur': 'Sakleshpur',
  'sakti': 'Sakti',
  'salem': 'Salem',
  'salempur': 'Salempur',
  'saltora': 'Saltora',
  'samalkha': 'Samalkha',
  'samana': 'Samana',
  'samastipur': 'Samastipur',
  'sambalpur': 'Sambalpur',
  'sambhal': 'Sambhal',
  'samrala': 'Samrala',
  'sanand': 'Sanand',
  'sangameshwar': 'Sangameshwar',
  'sangat': 'Sangat',
  'sangli': 'Sangli',
  'sangrur': 'Sangrur',
  'sankagiri': 'Sankagiri',
  'sankarapuram': 'Sankarapuram',
  'sankrail': 'Sankrail',
  'santipur': 'Santipur',
  'santrampur': 'Santrampur',
  'santuri': 'Santuri',
  'saoner': 'Saoner',
  'sarenga': 'Sarenga',
  'saroornagar': 'Saroornagar',
  'sasaram': 'Sasaram',
  'satara': 'Satara',
  'sathupalli': 'Sathupalli',
  'satna': 'Satna',
  'satpuli': 'Satpuli',
  'satyabadi': 'Satyabadi',
  'saundatti': 'Saundatti',
  'sausar': 'Sausar',
  'savanur': 'Savanur',
  'sawai-madhopur': 'Sawai Madhopur',
  'sawantwadi': 'Sawantwadi',
  'secunderabad': 'Secunderabad',
  'sedam': 'Sedam',
  'sehore': 'Sehore',
  'semiliguda': 'Semiliguda',
  'senthamangalam': 'Senthamangalam',
  'seoni': 'Seoni',
  'seraikela': 'Seraikela',
  'serampore': 'Serampore',
  'serchhip': 'Serchhip',
  'sewar': 'Sewar',
  'sewarhi': 'Sewarhi',
  'shahabad': 'Shahabad',
  'shahdol': 'Shahdol',
  'shahganj': 'Shahganj',
  'shahjahanpur': 'Shahjahanpur',
  'shahkot': 'Shahkot',
  'shahpur': 'Shahpur',
  'shamshabad': 'Shamshabad',
  'shantipur': 'Shantipur',
  'shegaon': 'Shegaon',
  'sheikhpura': 'Sheikhpura',
  'sheopur': 'Sheopur',
  'sheoraphuli': 'Sheoraphuli',
  'sherpur': 'Sherpur',
  'shiggaon': 'Shiggaon',
  'shikaripura': 'Shikaripura',
  'shikohabad': 'Shikohabad',
  'shillong': 'Shillong',
  'shimla': 'Shimla',
  'shimoga': 'Shimoga',
  'shirala': 'Shirala',
  'shivpuri': 'Shivpuri',
  'sholinganallur': 'Sholinganallur',
  'shoranur': 'Shoranur',
  'shorapur': 'Shorapur',
  'shravasti': 'Shravasti',
  'shrivardhan': 'Shrivardhan',
  'shyampur': 'Shyampur',
  'siddipet': 'Siddipet',
  'sidhwan-bet': 'Sidhwan Bet',
  'sidlaghatta': 'Sidlaghatta',
  'sihor': 'Sihor',
  'sihora': 'Sihora',
  'sikanderpur': 'Sikanderpur',
  'sikar': 'Sikar',
  'silchar': 'Silchar',
  'siliguri': 'Siliguri',
  'silvassa': 'Silvassa',
  'simdega': 'Simdega',
  'simlapal': 'Simlapal',
  'simulia': 'Simulia',
  'sinapali': 'Sinapali',
  'sindgi': 'Sindgi',
  'sindhanur': 'Sindhanur',
  'sindhudurg': 'Sindhudurg',
  'sindkhed-raja': 'Sindkhed Raja',
  'singareni': 'Singareni',
  'singrauli': 'Singrauli',
  'singur': 'Singur',
  'sira': 'Sira',
  'sirhind': 'Sirhind',
  'sirpur': 'Sirpur',
  'sirsa': 'Sirsa',
  'siruseri': 'Siruseri',
  'siswa-bazaar': 'Siswa Bazaar',
  'sitamarhi': 'Sitamarhi',
  'sitapur': 'Sitapur',
  'sitarganj': 'Sitarganj',
  'sivakasi': 'Sivakasi',
  'siwan': 'Siwan',
  'sohna': 'Sohna',
  'solan': 'Solan',
  'solapur': 'Solapur',
  'someshwar': 'Someshwar',
  'sonamukhi': 'Sonamukhi',
  'sonari': 'Sonari',
  'sonarpur': 'Sonarpur',
  'sonbhadra': 'Sonbhadra',
  'sonipat': 'Sonipat',
  'sopore': 'Sopore',
  'sorab': 'Sorab',
  'soro': 'Soro',
  'south-delhi': 'South Delhi',
  'sri-ganganagar': 'Sri Ganganagar',
  'sri-hargobindpur': 'Sri Hargobindpur',
  'srikakulam': 'Srikakulam',
  'srinagar': 'Srinagar',
  'sringeri': 'Sringeri',
  'srinivaspur': 'Srinivaspur',
  'sriperumbudur': 'Sriperumbudur',
  'station-ghanpur': 'Station Ghanpur',
  'sudhar': 'Sudhar',
  'sujangarh': 'Sujangarh',
  'sujanpur': 'Sujanpur',
  'sukma': 'Sukma',
  'sullia': 'Sullia',
  'sultan-bathery': 'Sultan Bathery',
  'sultanpur': 'Sultanpur',
  'sultanpur-lodhi': 'Sultanpur Lodhi',
  'sunabeda': 'Sunabeda',
  'sunam': 'Sunam',
  'sundernagar': 'Sundernagar',
  'supaul': 'Supaul',
  'surajpur': 'Surajpur',
  'surat': 'Surat',
  'surendranagar': 'Surendranagar',
  'surpur': 'Surpur',
  'suryapet': 'Suryapet',
  't-narasipur': 'T Narasipur',
  'tadepalligudem': 'Tadepalligudem',
  'tadipatri': 'Tadipatri',
  'talamadugu': 'Talamadugu',
  'talasari': 'Talasari',
  'taldangra': 'Taldangra',
  'taloja': 'Taloja',
  'talwandi-sabo': 'Talwandi Sabo',
  'talwara': 'Talwara',
  'tambaram': 'Tambaram',
  'tamkuhi-road': 'Tamkuhi Road',
  'tamluk': 'Tamluk',
  'tanakpur': 'Tanakpur',
  'tanda-urmur': 'Tanda Urmur',
  'tanur': 'Tanur',
  'tapukara': 'Tapukara',
  'tarakeswar': 'Tarakeswar',
  'taraori': 'Taraori',
  'tarikere': 'Tarikere',
  'tarn-taran': 'Tarn Taran',
  'tawang': 'Tawang',
  'tehri': 'Tehri',
  'tekulapalli': 'Tekulapalli',
  'telco': 'Telco',
  'tenali': 'Tenali',
  'tentulikhunti': 'Tentulikhunti',
  'tezpur': 'Tezpur',
  'tezu': 'Tezu',
  'thalaivasal': 'Thalaivasal',
  'thalassery': 'Thalassery',
  'thanagazi': 'Thanagazi',
  'thane': 'Thane',
  'thanesar': 'Thanesar',
  'thanjavur': 'Thanjavur',
  'tharali': 'Tharali',
  'thirunavalur': 'Thirunavalur',
  'thiruporur': 'Thiruporur',
  'thiruvalla': 'Thiruvalla',
  'thiruvananthapuram': 'Thiruvananthapuram',
  'thiruverkadu': 'Thiruverkadu',
  'thodupuzha': 'Thodupuzha',
  'thoothukudi': 'Thoothukudi',
  'thorrur': 'Thorrur',
  'thoubal': 'Thoubal',
  'thrissur': 'Thrissur',
  'thuamul-rampur': 'Thuamul Rampur',
  'tihidi': 'Tihidi',
  'tijara': 'Tijara',
  'tikamgarh': 'Tikamgarh',
  'tindivanam': 'Tindivanam',
  'tinsukia': 'Tinsukia',
  'tiptur': 'Tiptur',
  'tirthahalli': 'Tirthahalli',
  'tirtol': 'Tirtol',
  'tiruchengode': 'Tiruchengode',
  'tiruchirappalli': 'Tiruchirappalli',
  'tirukoilur': 'Tirukoilur',
  'tirunelveli': 'Tirunelveli',
  'tirupati': 'Tirupati',
  'tirupattur': 'Tirupattur',
  'tiruppur': 'Tiruppur',
  'tirur': 'Tirur',
  'tiruttani': 'Tiruttani',
  'tiruvannamalai': 'Tiruvannamalai',
  'tiruvottiyur': 'Tiruvottiyur',
  'tiryani': 'Tiryani',
  'titagarh': 'Titagarh',
  'tohana': 'Tohana',
  'tonk': 'Tonk',
  'tuensang': 'Tuensang',
  'tulsipur': 'Tulsipur',
  'tumkur': 'Tumkur',
  'tura': 'Tura',
  'turtipar': 'Turtipar',
  'turuvekere': 'Turuvekere',
  'uchhain': 'Uchhain',
  'udaipur': 'Udaipur',
  'udaynarayanpur': 'Udaynarayanpur',
  'udgir': 'Udgir',
  'udhagamandalam': 'Udhagamandalam',
  'udhampur': 'Udhampur',
  'udupi': 'Udupi',
  'ujjain': 'Ujjain',
  'ulhasnagar': 'Ulhasnagar',
  'uluberia': 'Uluberia',
  'ulundurpet': 'Ulundurpet',
  'umaria': 'Umaria',
  'umarkote': 'Umarkote',
  'umred': 'Umred',
  'umreth': 'Umreth',
  'una': 'Una',
  'unjha': 'Unjha',
  'unnao': 'Unnao',
  'upleta': 'Upleta',
  'uppal': 'Uppal',
  'uran': 'Uran',
  'urapakkam': 'Urapakkam',
  'uska-bazaar': 'Uska Bazaar',
  'uthangarai': 'Uthangarai',
  'uthiramerur': 'Uthiramerur',
  'uthukkottai': 'Uthukkottai',
  'utnoor': 'Utnoor',
  'utraula': 'Utraula',
  'uttarkashi': 'Uttarkashi',
  'uttarpara': 'Uttarpara',
  'vadakara': 'Vadakara',
  'vadodara': 'Vadodara',
  'vaikom': 'Vaikom',
  'valasaravakkam': 'Valasaravakkam',
  'valsad': 'Valsad',
  'vanasthalipuram': 'Vanasthalipuram',
  'vandalur': 'Vandalur',
  'vandavasi': 'Vandavasi',
  'vaniyambadi': 'Vaniyambadi',
  'vanur': 'Vanur',
  'vapi': 'Vapi',
  'varanasi': 'Varanasi',
  'varkala': 'Varkala',
  'vasai-virar': 'Vasai-Virar',
  'vasco-da-gama': 'Vasco da Gama',
  'vatakara': 'Vatakara',
  'velachery': 'Velachery',
  'vellore': 'Vellore',
  'velur': 'Velur',
  'vengurla': 'Vengurla',
  'venkatapuram': 'Venkatapuram',
  'veraval': 'Veraval',
  'verka': 'Verka',
  'vidisha': 'Vidisha',
  'vijayawada': 'Vijayawada',
  'vijaypur': 'Vijaypur',
  'vikasnagar': 'Vikasnagar',
  'vikramgad': 'Vikramgad',
  'viluppuram': 'Viluppuram',
  'vinukonda': 'Vinukonda',
  'viramgam': 'Viramgam',
  'virudhunagar': 'Virudhunagar',
  'visakhapatnam': 'Visakhapatnam',
  'visavadar': 'Visavadar',
  'visnagar': 'Visnagar',
  'vizianagaram': 'Vizianagaram',
  'vrindavan': 'Vrindavan',
  'wada': 'Wada',
  'wadakkancherry': 'Wadakkancherry',
  'wai': 'Wai',
  'walajabad': 'Walajabad',
  'wankaner': 'Wankaner',
  'wankidi': 'Wankidi',
  'warangal': 'Warangal',
  'waraseoni': 'Waraseoni',
  'wardha': 'Wardha',
  'wardhannapet': 'Wardhannapet',
  'washim': 'Washim',
  'weir': 'Weir',
  'west-delhi': 'West Delhi',
  'williamnagar': 'Williamnagar',
  'wokha': 'Wokha',
  'wyra': 'Wyra',
  'yadagirigutta': 'Yadagirigutta',
  'yadgir': 'Yadgir',
  'yamkeshwar': 'Yamkeshwar',
  'yamunanagar': 'Yamunanagar',
  'yamunotri': 'Yamunotri',
  'yanam': 'Yanam',
  'yavatmal': 'Yavatmal',
  'yelandur': 'Yelandur',
  'yelburga': 'Yelburga',
  'yellandu': 'Yellandu',
  'yercaud': 'Yercaud',
  'zamania': 'Zamania',
  'zira': 'Zira',
  'zirakpur': 'Zirakpur',
  'ziro': 'Ziro',
  'zunheboto': 'Zunheboto'
};

// Streams (slug format)
export const STREAMS = [
  'engineering', 'medical', 'management', 'law', 'arts', 'science', 'commerce',
  'pharmacy', 'architecture', 'design', 'agriculture', 'education', 'nursing',
  'dental', 'hotel-management', 'mass-communication', 'computer-applications',
  'aviation', 'animation', 'fashion-design', 'interior-design', 'journalism',
  'humanities', 'social-sciences', 'fine-arts', 'performing-arts', 'media',
  'hospitality', 'tourism', 'allied-health', 'paramedical', 'veterinary',
  'ayurveda', 'homeopathy', 'unani', 'yoga', 'naturopathy'
];

// Stream name mapping (slug to display name)
export const STREAM_NAMES = {
  'engineering': 'Engineering',
  'medical': 'Medical',
  'management': 'Management',
  'law': 'Law',
  'arts': 'Arts',
  'science': 'Science',
  'commerce': 'Commerce',
  'pharmacy': 'Pharmacy',
  'architecture': 'Architecture',
  'design': 'Design',
  'agriculture': 'Agriculture',
  'education': 'Education',
  'nursing': 'Nursing',
  'dental': 'Dental',
  'hotel-management': 'Hotel Management',
  'mass-communication': 'Mass Communication',
  'computer-applications': 'Computer Applications',
  'aviation': 'Aviation',
  'animation': 'Animation',
  'fashion-design': 'Fashion Design',
  'interior-design': 'Interior Design',
  'journalism': 'Journalism',
  'humanities': 'Humanities',
  'social-sciences': 'Social Sciences',
  'fine-arts': 'Fine Arts',
  'performing-arts': 'Performing Arts',
  'media': 'Media',
  'hospitality': 'Hospitality',
  'tourism': 'Tourism',
  'allied-health': 'Allied Health',
  'paramedical': 'Paramedical',
  'veterinary': 'Veterinary',
  'ayurveda': 'Ayurveda',
  'homeopathy': 'Homeopathy',
  'unani': 'Unani',
  'yoga': 'Yoga',
  'naturopathy': 'Naturopathy'
};

// Courses (slug format)
export const COURSES = [
  'btech', 'be', 'mtech', 'me', 'mbbs', 'bds', 'bams', 'bhms', 'bpharm', 'dpharm',
  'mba', 'bba', 'pgdm', 'bms', 'bbm', 'bcom', 'mcom', 'ca', 'cs',
  'bsc', 'msc', 'ba', 'ma', 'bca', 'mca', 'llb', 'llm', 'ballb', 'bballb',
  'barch', 'march', 'bdes', 'mdes', 'bjmc', 'bhm', 'bed', 'med', 'phd',
  'diploma', 'polytechnic', 'iti', 'bvoc', 'mvoc',
  'bfa', 'mfa', 'bpe', 'mpe', 'blib', 'mlib',
  'md', 'ms', 'dm', 'mch', 'bpt', 'mpt', 'bot', 'mot',
  'bsc-nursing', 'msc-nursing', 'gnm', 'anm',
  'bba-llb', 'bcom-llb', 'ba-llb'
];

// Course name mapping (slug to display name)
export const COURSE_NAMES = {
  'btech': 'B.Tech',
  'be': 'B.E',
  'mtech': 'M.Tech',
  'me': 'M.E',
  'mbbs': 'MBBS',
  'bds': 'BDS',
  'bams': 'BAMS',
  'bhms': 'BHMS',
  'bpharm': 'B.Pharm',
  'dpharm': 'D.Pharm',
  'mba': 'MBA',
  'bba': 'BBA',
  'pgdm': 'PGDM',
  'bms': 'BMS',
  'bbm': 'BBM',
  'bcom': 'B.Com',
  'mcom': 'M.Com',
  'ca': 'CA',
  'cs': 'CS',
  'bsc': 'B.Sc',
  'msc': 'M.Sc',
  'ba': 'BA',
  'ma': 'MA',
  'bca': 'BCA',
  'mca': 'MCA',
  'llb': 'LLB',
  'llm': 'LLM',
  'ballb': 'BA LLB',
  'bballb': 'BBA LLB',
  'barch': 'B.Arch',
  'march': 'M.Arch',
  'bdes': 'B.Des',
  'mdes': 'M.Des',
  'bjmc': 'BJMC',
  'bhm': 'BHM',
  'bed': 'B.Ed',
  'med': 'M.Ed',
  'phd': 'PhD',
  'diploma': 'Diploma',
  'polytechnic': 'Polytechnic',
  'iti': 'ITI',
  'md': 'MD',
  'ms': 'MS',
  'bpt': 'BPT',
  'mpt': 'MPT',
  'bsc-nursing': 'B.Sc Nursing',
  'msc-nursing': 'M.Sc Nursing',
  'gnm': 'GNM',
  'anm': 'ANM'
};

// Check functions
export const isState = (slug) => INDIAN_STATES.includes(slug?.toLowerCase());
export const isCity = (slug) => INDIAN_CITIES.includes(slug?.toLowerCase());
export const isStream = (slug) => STREAMS.includes(slug?.toLowerCase());
export const isCourse = (slug) => COURSES.includes(slug?.toLowerCase());

// Get display name functions
export const getStateName = (slug) => STATE_NAMES[slug?.toLowerCase()] || slug;
export const getCityName = (slug) => CITY_NAMES[slug?.toLowerCase()] || slug;
export const getStreamName = (slug) => STREAM_NAMES[slug?.toLowerCase()] || slug;
export const getCourseName = (slug) => COURSE_NAMES[slug?.toLowerCase()] || slug;

/**
 * Identify what type of segment this is
 * Priority: STATE > CITY > STREAM > COURSE
 */
export const identifySegment = (slug) => {
  if (!slug) return { type: 'unknown', value: null };
  
  const lowerSlug = slug.toLowerCase();
  
  if (isState(lowerSlug)) {
    return { type: 'state', value: lowerSlug, displayName: getStateName(lowerSlug) };
  }
  if (isCity(lowerSlug)) {
    return { type: 'city', value: lowerSlug, displayName: getCityName(lowerSlug) };
  }
  if (isStream(lowerSlug)) {
    return { type: 'stream', value: lowerSlug, displayName: getStreamName(lowerSlug) };
  }
  if (isCourse(lowerSlug)) {
    return { type: 'course', value: lowerSlug, displayName: getCourseName(lowerSlug) };
  }
  
  return { type: 'unknown', value: lowerSlug };
};

/**
 * Parse the new URL structure
 * 
 * /university - All universities
 * /university/west-bengal - State
 * /university/kolkata - City
 * /university/west-bengal/kolkata - State+City
 * /university/engineering - Stream
 * /university/btech - Course
 * /university/engineering/btech - Stream+Course
 * /university/west-bengal/engineering - State+Stream
 * /university/kolkata/engineering - City+Stream
 * /university/west-bengal/engineering/btech - State+Stream+Course
 * /university/kolkata/engineering/btech - City+Stream+Course
 * 
 * Same for /colleges and /schools
 */
export const parseInstitutionUrl = (pathname) => {
  const parts = pathname.split('/').filter(Boolean);
  
  if (parts.length === 0) {
    return { type: 'home' };
  }
  
  const institutionType = parts[0]; // 'university', 'colleges', 'schools'
  
  // Check if it's a valid institution type
  if (!['university', 'colleges', 'schools'].includes(institutionType)) {
    return { type: 'unknown', parts };
  }
  
  const result = {
    type: 'institution-listing',
    institutionType: institutionType,
    state: null,
    city: null,
    stream: null,
    course: null,
    filters: {}
  };
  
  // No additional segments - show all
  if (parts.length === 1) {
    return result;
  }
  
  // Parse remaining segments
  const segments = parts.slice(1);
  
  // Identify each segment
  const identified = segments.map(seg => identifySegment(seg));
  
  // Build filters based on identified segments
  for (const seg of identified) {
    switch (seg.type) {
      case 'state':
        if (!result.state) {
          result.state = seg.value;
          result.filters.state = seg.displayName;
        }
        break;
      case 'city':
        if (!result.city) {
          result.city = seg.value;
          result.filters.city = seg.displayName;
        }
        break;
      case 'stream':
        if (!result.stream) {
          result.stream = seg.value;
          result.filters.stream = seg.displayName;
        }
        break;
      case 'course':
        if (!result.course) {
          result.course = seg.value;
          result.filters.course = seg.displayName;
        }
        break;
      default:
        // Unknown segment - could be a detail page ID
        if (seg.value && seg.value.match(/^\d+-/)) {
          // This is a detail page: /colleges/001-iit-bombay
          return {
            type: 'institution-detail',
            institutionType: institutionType,
            idSlug: seg.value
          };
        }
        break;
    }
  }
  
  return result;
};

/**
 * Generate page title based on parsed URL
 */
export const generatePageTitle = (parsed) => {
  if (parsed.type !== 'institution-listing') return '';
  
  const parts = [];
  
  // Add course if present
  if (parsed.filters.course) {
    parts.push(parsed.filters.course);
  }
  
  // Add stream if present
  if (parsed.filters.stream) {
    parts.push(parsed.filters.stream);
  }
  
  // Institution type
  const typeLabel = {
    'university': 'Universities',
    'colleges': 'Colleges',
    'schools': 'Schools'
  }[parsed.institutionType] || 'Institutions';
  
  parts.push(typeLabel);
  
  // Add location
  if (parsed.filters.city && parsed.filters.state) {
    parts.push(`in ${parsed.filters.city}, ${parsed.filters.state}`);
  } else if (parsed.filters.city) {
    parts.push(`in ${parsed.filters.city}`);
  } else if (parsed.filters.state) {
    parts.push(`in ${parsed.filters.state}`);
  } else {
    parts.push('in India');
  }
  
  return parts.join(' ');
};

/**
 * Generate meta description based on parsed URL
 */
export const generateMetaDescription = (parsed, count = 0) => {
  if (parsed.type !== 'institution-listing') return '';
  
  const typeLabel = {
    'university': 'universities',
    'colleges': 'colleges',
    'schools': 'schools'
  }[parsed.institutionType] || 'institutions';
  
  let location = 'India';
  if (parsed.filters.city && parsed.filters.state) {
    location = `${parsed.filters.city}, ${parsed.filters.state}`;
  } else if (parsed.filters.city) {
    location = parsed.filters.city;
  } else if (parsed.filters.state) {
    location = parsed.filters.state;
  }
  
  let offering = '';
  if (parsed.filters.course && parsed.filters.stream) {
    offering = ` offering ${parsed.filters.course} in ${parsed.filters.stream}`;
  } else if (parsed.filters.stream) {
    offering = ` for ${parsed.filters.stream}`;
  } else if (parsed.filters.course) {
    offering = ` offering ${parsed.filters.course}`;
  }
  
  const countText = count > 0 ? `Explore ${count}+ ` : 'Find the best ';
  
  return `${countText}${typeLabel}${offering} in ${location}. Compare fees, placements, rankings, and admission details.`;
};

// Legacy exports for backward compatibility
export { generateSlug };

export const getInstitutionListingUrl = (type, location = null) => {
  const suffix = type?.toLowerCase() === 'university' ? 'university' : 
                 type?.toLowerCase() === 'school' ? 'schools' : 'colleges';
  
  if (!location) {
    return `/${suffix}`;
  }
  
  const locationSlug = generateSlug(location);
  return `/${suffix}/${locationSlug}`;
};

export const getInstitutionDetailUrl = (type, id, name, city = null, serialNumber = null) => {
  const typeSuffix = type?.toLowerCase() === 'university' ? 'university' : 
                     type?.toLowerCase() === 'school' ? 'schools' : 'colleges';
  const nameSlug = generateSlug(name);
  
  let numericId;
  if (serialNumber) {
    numericId = String(serialNumber).padStart(3, '0');
  } else {
    const idMatch = id?.match(/(\d+)$/);
    numericId = idMatch ? idMatch[1] : '000';
  }
  
  let finalSlug = nameSlug;
  if (city) {
    const citySlug = generateSlug(city);
    const mainCityPart = citySlug.split('-').pop();
    const nameHasCity = nameSlug.toLowerCase().includes(citySlug.toLowerCase()) || 
                        nameSlug.toLowerCase().includes(mainCityPart.toLowerCase());
    if (!nameHasCity) {
      finalSlug = `${nameSlug}-${citySlug}`;
    }
  }
  
  return `/${typeSuffix}/${numericId}-${finalSlug}`;
};

export default {
  generateSlug,
  parseInstitutionUrl,
  generatePageTitle,
  generateMetaDescription,
  identifySegment,
  isState,
  isCity,
  isStream,
  isCourse,
  getStateName,
  getCityName,
  getStreamName,
  getCourseName,
  getInstitutionListingUrl,
  getInstitutionDetailUrl,
  INDIAN_STATES,
  INDIAN_CITIES,
  STREAMS,
  COURSES,
  STATE_NAMES,
  CITY_NAMES,
  STREAM_NAMES,
  COURSE_NAMES,
  INSTITUTION_TYPES
};
